import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import{bootstrapTask}from"../../tools/cli/task-bootstrap.mjs";
const cli=new URL("../../tools/cli/stage-runtime.mjs",import.meta.url).href;
async function fixture(){const r=root(),repo=join(r,"repo"),storage=join(r,"storage"),home=join(r,"home");repository(repo);mkdirSync(storage);mkdirSync(home);const boot=await bootstrapTask({project:"OwnedEntry",task:"current-entry", "target-repo":repo},{env:{HOME:home,WORKFLOWHUB_TASK_DIR:storage},home,cwd:repo});const wt=boot.workspace.worktree_root,material=join(wt,"specs/current-entry");mkdirSync(join(material,"phases"),{recursive:true});for(const[name,text]of Object.entries({"decision-log.md":"# Current decision\n\n## 任务身份\n- **任务类型**：普通任务\n", "spec.md":"# Current specification\n", "phases/index.md":"## Execution Index\n\n| phase | authority ref | semantic anchor | write set | dependency | consumer |\n| --- | --- | --- | --- | --- | --- |\n| `P1` | `phases/P1.md` | owned | README.md | none | build-code |\n", "phases/P1.md":"# Phase P1\n\n### T001 — Owned current task\n"}))writeFileSync(join(material,name),text);git(wt,"add","specs");git(wt,"commit","-qm","owned current materials");return{r,repo,storage,home,wt,material,taskPath:boot.task_path,n:0};}
function call(f,behavior,action,{stage="build-code",input,extra=[],review=false}={}){const argv=[behavior,`--action=${action}`,`--stage=${stage}`,"--project=OwnedEntry","--task=current-entry",`--task-path=${f.taskPath}`,...extra];if(input!==undefined){const p=join(f.wt,`input-${++f.n}.json`);writeFileSync(p,JSON.stringify(input)+"\n");argv.push(`--input=${p}`);}const code=`import{stageRuntimeCliMain}from${JSON.stringify(cli)};try{const value=await stageRuntimeCliMain(JSON.parse(process.argv[1]),${review?'{services:{runReviewRound:async(request,options)=>{await options.onProviderOutput({provider:"owned/stub",output:Buffer.from([0xff,0x00,0x41])});return{status:"unavailable",dispatch_state:"unknown",findings:[],provider_results:[],error:{code:"OWNED_UNAVAILABLE",message:"controlled no-model review"}};}}}':'{}'});console.log(JSON.stringify({ok:true,value}));}catch(error){console.log(JSON.stringify({ok:false,error:{code:error.code??null,message:error.message}}));}`;const result=spawnSync(process.execPath,["--input-type=module","-e",code,JSON.stringify(argv)],{cwd:f.wt,env:{...env(),HOME:f.home,XDG_CONFIG_HOME:join(f.home,".config"),WORKFLOWHUB_TASK_DIR:f.storage},encoding:"utf8",timeout:15000,stdio:["ignore","pipe","pipe"]});expect(result.error).toBeUndefined();expect(result.status).toBe(0);return JSON.parse(result.stdout);}
function originalFacts(f){return readFileSync(join(f.taskPath,"facts.jsonl"));}
describe("real owned child chain across seven public behaviors",()=>{
 it("doctor/status reads real current material and reports quality unknown without a stage outcome",async()=>{const f=await fixture(),before=originalFacts(f);const doctor=call(f,"doctor","workspace");expect(doctor).toMatchObject({ok:true,value:{task_id:"current-entry",worktree_root:f.wt}});const status=call(f,"status","begin");expect(status).toMatchObject({ok:true,value:{work_status:"ready",quality_status:"unknown",facts:[]}});expect(originalFacts(f)).toEqual(before);});
 it("run drafts exact authored bytes then stores only the navigation cursor",async()=>{const f=await fixture(),draft=join(f.wt,"owned-spec.md"),bytes=Buffer.from("# Revised owned specification\r\n");writeFileSync(draft,bytes);const result=call(f,"run","draft",{stage:"build-plan",extra:["--name=spec.md",`--input=${draft}`]});expect(result.ok).toBe(true);expect(readFileSync(join(f.material,"spec.md"))).toEqual(bytes);const cursor=call(f,"run","execute",{input:{phase_progress:{phase_id:"P1",task_id:"T001"}}});expect(cursor).toMatchObject({ok:true,value:{status:"recorded"}});const status=call(f,"status","begin");expect(status.value.quality_status).toBe("unknown");expect(status.value.facts).toHaveLength(1);expect(status.value.facts[0]).not.toHaveProperty("completed");});
 it("cross-stage reads the actual current decision and exposes exact missing Phase without inventing a report",async()=>{const f=await fixture(),before=originalFacts(f),decision=join(f.material,"decision-log.md");rmSync(decision);const planning=call(f,"status","begin",{stage:"build-plan"});expect(planning.value).toMatchObject({work_status:"not_ready",quality_status:"unknown",missing_materials:["decision-log.md"]});writeFileSync(decision,"# Current replacement direction\n");expect(call(f,"status","begin",{stage:"build-plan"}).value.work_status).toBe("ready");rmSync(join(f.material,"phases/P1.md"));expect(call(f,"status","begin").value.missing_materials).toEqual(["phases/P1.md"]);expect(originalFacts(f)).toEqual(before);expect(existsSync(join(f.taskPath,"quality/evidence/stage-outcomes"))).toBe(false);});
 it("review retains unavailable process facts and exact original raw rather than available quality",async()=>{const f=await fixture(),before=originalFacts(f),result=call(f,"review","record",{review:true,input:{request:{stage:"build-code",review_scope:"phase",phase_id:"P1",subject_kind:"phase",surface:"document",subject:{paths:["spec.md"]},materials:{approved_spec:"# Owned current spec"}}}});expect(result).toMatchObject({ok:true,value:{status:"unavailable",authoritative:false}});const record=JSON.parse(readFileSync(join(f.taskPath,result.value.result_ref)));expect(record.error.code).toBe("OWNED_UNAVAILABLE");expect(record.request.subject).toEqual({paths:["spec.md"]});const raws=readdirSync(join(f.taskPath,"quality/reviews")).filter(n=>n.endsWith(".output"));expect(raws).toHaveLength(1);expect(readFileSync(join(f.taskPath,"quality/reviews",raws[0]))).toEqual(Buffer.from([0xff,0x00,0x41]));expect(originalFacts(f)).toEqual(before);expect(call(f,"status","begin").value.quality_status).toBe("unknown");});
 it("verify captures real failure output while confirm and authorize preserve human reply and current Git identity",async()=>{const f=await fixture(),head=git(f.wt,"rev-parse","HEAD"),before=originalFacts(f);const verify=call(f,"verify","execute",{input:{slug:"owned-real-command",argv:[process.execPath,"-e",'process.stdout.write("actual-output");process.stderr.write("actual-error");process.exit(3);']}});expect(verify).toMatchObject({ok:true,value:{exit_code:3}});expect(readFileSync(verify.value.output_ref,"utf8")).toContain("actual-error");const confirm=call(f,"confirm","decision",{extra:["--decision=approved","--reply-text=确切的原始同意文本","--material-ref=spec.md"]});expect(confirm.ok).toBe(true);const confirmation=JSON.parse(readFileSync(confirm.value.path));expect(confirmation).toMatchObject({reply:"确切的原始同意文本",head});const authorize=call(f,"authorize","commit",{extra:[`--subject-ref=${confirm.value.path}`]});expect(authorize.ok).toBe(true);expect(JSON.parse(readFileSync(authorize.value.path))).toMatchObject({operation:"commit",head,confirmation_ref:confirm.value.path});expect(git(f.wt,"rev-parse","HEAD")).toBe(head);expect(originalFacts(f)).toEqual(before);});
});
