// Finding dispositions remain human facts; risk-card/snapshot/completion machines retire.
import {expect,it} from "vitest";
import {canonicalReviewFindings,deriveSeriousReviewPause,buildRiskAcceptance,validateRiskAcceptance,validateRiskAcceptanceSet,validateReportableFindingDispositions}from"../runtime/review/stage-review-disposition.mjs";
const finding={id:"finding-1",severity:"major",evidence_status:"direct",issue:"Actual serious defect",path:"src/current.mjs",root_cause:"actual source"};
const review={task_id:"risk-task",stage:"build-code",status:"available",findings:[finding]};const pause=()=>deriveSeriousReviewPause({taskId:"risk-task",stage:"build-code",reviewRef:"quality/reviews/current.json",result:review});
const item=status=>({finding_id:"finding-1",status,original_fact:"Actual serious defect",source:"review",consequence:"Incorrect delivery",next_action:"Repair or decide"});
const reply={finding_id:"finding-1",reply:"I accept this specific consequence.",reply_ref:"quality/evidence/human-confirmations/current.json"};
it("uses explicit reportable findings instead of non-adopted clusters and respects an explicitly empty list",()=>{expect(canonicalReviewFindings({...review,adjudication:{clusters:[{issue:"not adopted"}]}})).toEqual([finding]);expect(canonicalReviewFindings({findings:[],adjudication:{clusters:[finding]}})).toEqual([]);});
it("exposes malformed findings instead of silently treating them as empty",()=>{expect(()=>canonicalReviewFindings({findings:{}})).toThrow(/must be an array/);});
it("keeps unavailable/incomplete reviews unknown rather than manufacturing clean quality",()=>{for(const status of["unavailable","incomplete","unknown"]){const r=validateReportableFindingDispositions({result:{...review,status}});expect(r.facts.status).toBe(status);expect(r.missing_items.length).toBeGreaterThan(0);}});
it("preserves actual serious issue, scope, consequences and the explicit user choice",()=>{const p=pause();expect(p.status).toBe("needs_human");expect(p.findings[0]).toMatchObject({finding_id:"finding-1",issue:finding.issue,impact_scope:[finding.path]});const a=buildRiskAcceptance({pause:p,findingId:"finding-1",selectedOption:"accept-risk",replyRef:reply.reply_ref,reply:reply.reply,acceptedAt:"2026-10-03T00:00:00Z"});expect(validateRiskAcceptance({acceptance:a,pause:p})).toEqual(a);expect(a.reply).toBe(reply.reply);expect(()=>validateRiskAcceptance({acceptance:{...a,task_id:"another"},pause:p})).toThrow(/scope mismatch/);});
it("does not accept a non-risk option or invented blank human reply",()=>{for(const delta of[{selectedOption:"repair"},{reply:""},{replyRef:""}])expect(()=>buildRiskAcceptance({pause:pause(),findingId:"finding-1",selectedOption:"accept-risk",replyRef:reply.reply_ref,reply:reply.reply,acceptedAt:"2026-10-03T00:00:00Z",...delta})).toThrow();});
it("keeps accepted_risk incomplete without both an explicit authorization and real reply fact",()=>{for(const args of[{}, {authorizedRiskFindingIds:["finding-1"]},{userReply:reply}])expect(validateReportableFindingDispositions({result:review,dispositions:[item("accepted_risk")],...args}).facts.status).toBe("incomplete");expect(validateReportableFindingDispositions({result:review,dispositions:[item("accepted_risk")],authorizedRiskFindingIds:["finding-1"],userReply:reply}).facts.status).toBe("recorded");});
it("requires user_decided to retain the matching verbatim human source",()=>{expect(()=>validateReportableFindingDispositions({result:review,dispositions:[item("user_decided")],userReply:reply})).toThrow(/source=user_reply/);expect(validateReportableFindingDispositions({result:review,dispositions:[{...item("user_decided"),source:"user_reply"}],userReply:reply}).facts.status).toBe("recorded");});
it("rejects unknown or duplicate dispositions and incomplete acceptance sets",()=>{expect(()=>validateReportableFindingDispositions({result:review,dispositions:[item("fixed"),item("fixed")]})).toThrow(/duplicate/);expect(()=>validateReportableFindingDispositions({result:review,dispositions:[{...item("fixed"),finding_id:"other"}]})).toThrow(/unknown/);expect(()=>validateRiskAcceptanceSet({acceptances:[],pause:pause()})).toThrow(/every actual serious finding/);const a=buildRiskAcceptance({pause:pause(),findingId:"finding-1",selectedOption:"accept-risk",replyRef:reply.reply_ref,reply:reply.reply,acceptedAt:"2026-10-03T00:00:00Z"});expect(()=>validateRiskAcceptanceSet({acceptances:[a,a],pause:pause()})).toThrow(/duplicate/);});
