import {createHash} from "node:crypto";
import {afterEach,expect,test} from "vitest";
import {spawnSync} from "node:child_process";
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,rmSync,realpathSync,symlinkSync} from "node:fs";
import {tmpdir} from "node:os";import {join} from "node:path";
const roots=[];afterEach(()=>{for(const r of roots.splice(0))rmSync(r,{recursive:true,force:true});});
function invoke({tools=[],human=[],platform=[],provider=[],since=0,until=1000}={}){const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-ledger-")));roots.push(root);writeFileSync(join(root,"owned.md"),"owned source");symlinkSync(join(root,"owned.md"),join(root,"alias.md"));const rows=[{type:"turn/start",time:0,data:{}}];let id=0;for(const [start,end] of tools){const callId="tool"+id++;rows.push({type:"tool/call",time:start,data:{name:"exec_command",callId,arguments:{cmd:id===1?"cat ./owned.md":"sed -n '1,3p' alias.md",cwd:root}}},{type:"tool/result",time:end,data:{callId}});}for(const [start,end] of human){const callId="ask"+id++;rows.push({type:"tool/call",time:start,data:{name:"ask_user_question",callId}},{type:"tool/result",time:end,data:{callId}});}for(const [start,end] of platform)rows.push({type:"turn/start",time:start,data:{}},{type:"turn/end",time:end,data:{reason:{kind:"aborted"},error:"safety policy interruption"}});rows.sort((a,b)=>a.time-b.time);const source=join(root,"session.jsonl");writeFileSync(source,rows.map(r=>JSON.stringify(r)).join("\n")+"\n");const reviews=join(root,"reviews");mkdirSync(reviews);writeFileSync(join(reviews,"review.json"),JSON.stringify({provider_results:provider.map(([started_at_ms,completed_at_ms])=>({timing:{started_at_ms,completed_at_ms}}))},null,2));const result=spawnSync(process.execPath,[join(import.meta.dirname,"card-09-session-ledger.mjs"),"--session",source,"--since",String(since),"--until",String(until),"--reviews",reviews],{encoding:"utf8"});expect(result.error).toBeUndefined();expect(result.stdout,result.stderr).toBeTruthy();return{result,value:JSON.parse(result.stdout)};}
const cases=[
 ["overlapping provider intervals use union",{provider:[[0,600],[400,1000]]},{platform_interrupt:0,human_wait:0,provider_activity:1000,tool_subagent:0,unattributed:0}],
 ["human waiting overrides overlapping provider",{human:[[200,700]],provider:[[0,1000]]},{platform_interrupt:0,human_wait:500,provider_activity:500,tool_subagent:0,unattributed:0}],
 ["platform interruption overrides human/provider",{platform:[[300,600]],human:[[100,800]],provider:[[0,1000]]},{platform_interrupt:300,human_wait:400,provider_activity:300,tool_subagent:0,unattributed:0}],
 ["overlapping tools are counted once with unattributed remainder",{tools:[[100,500],[300,700]]},{platform_interrupt:0,human_wait:0,provider_activity:0,tool_subagent:600,unattributed:400}],
 ["empty clipped time window is zero",{tools:[[0,1000]],provider:[[0,1000]],since:500,until:500},{platform_interrupt:0,human_wait:0,provider_activity:0,tool_subagent:0,unattributed:0}],
];test.each(cases)("%s",(_name,input,expected)=>{const {result,value}=invoke(input);expect(value.accounting_ms).toEqual(expected);expect(value.accounted_ms).toBe(value.window.span_ms);expect(value.self_check).toBe(true);expect(result.status).toBe(0);expect(value.sources).toHaveLength(2);for(const source of value.sources)expect(source.sha256).toMatch(/^[a-f0-9]{64}$/);});
test("counts only actual calls and repeat reads inside the requested window",()=>{const {value}=invoke({tools:[[100,200],[300,400]],human:[[500,600]]});expect(value.counts).toMatchObject({tool_calls:3,human_questions:1,main_self_execution:2,same_path_repeat_reads:1});});

test("wrapper code and rg patterns do not fabricate inner execution or repeated-path reads",()=>{const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-ledger-wrapper-")));roots.push(root);const path=join(root,"session.jsonl");writeFileSync(path,[{type:"tool/call",time:0,data:{name:"functions.exec",callId:"wrapper",arguments:{code:"await tools.exec_command({cmd:'cat /private/source'})"}}},{type:"tool/result",time:100,data:{callId:"wrapper"}},{type:"tool/call",time:20,data:{name:"exec_command",callId:"search",arguments:{cmd:"rg secret-pattern /private/source",cwd:root}}},{type:"tool/result",time:50,data:{callId:"search"}}].map(r=>JSON.stringify(r)).join("\n"));const r=spawnSync(process.execPath,[join(import.meta.dirname,"card-09-session-ledger.mjs"),"--session",path,"--since","0","--until","100"],{encoding:"utf8"});const value=JSON.parse(r.stdout);expect(value.counts.main_self_execution).toBe(1);expect(value.counts.same_path_repeat_reads).toBe(0);expect(value.status).toBe("inconclusive");expect(value.coverage_limits).toContain("wrapper execution cannot establish inner execution/read counts");expect(value.coverage_limits).toContain("rg pattern/path ambiguity: repeated reads not inferred");});

test("streams a real compressed DSH metadata input and hashes its original compressed bytes",()=>{const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-ledger-zstd-")));roots.push(root);const plain=join(root,"input.jsonl"),packed=join(root,"session.v4.jsonl.zstd");writeFileSync(plain,[{type:"tool/call",time:0,data:{name:"ask_user_question",callId:"human"}},{type:"tool/result",time:100,data:{callId:"human"}}].map(r=>JSON.stringify(r)).join("\n"));const compress=spawnSync("zstd",["-q","-f",plain,"-o",packed],{encoding:"utf8"});expect(compress.error).toBeUndefined();expect(compress.status,compress.stderr).toBe(0);const r=spawnSync(process.execPath,[join(import.meta.dirname,"card-09-session-ledger.mjs"),"--session",packed,"--since","0","--until","100"],{encoding:"utf8"});expect(r.status,r.stderr).toBe(0);const value=JSON.parse(r.stdout);expect(value.accounting_ms).toMatchObject({human_wait:100,unattributed:0});expect(value.sources[0].schema).toBe("dsh");expect(value.sources[0].sha256).toBe(createHash("sha256").update(readFileSync(packed)).digest("hex"));});

// F02/F03: actual CLI fixtures; existing eight scoring cases remain unchanged.
function reviewFixRoot(){const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-ledger-review-")));roots.push(root);writeFileSync(join(root,"owned.md"),"owned source");return root;}
function runReviewLedger(path){const r=spawnSync(process.execPath,[join(import.meta.dirname,"card-09-session-ledger.mjs"),"--session",path,"--since","100","--until","1000"],{encoding:"utf8"});expect(r.error).toBeUndefined();expect(r.status,r.stderr).toBe(0);return JSON.parse(r.stdout);}
function callsFor(cmds,cwd){return cmds.flatMap((cmd,index)=>[{type:"tool/call",time:100+index*100,data:{name:"exec_command",callId:"call-"+index,arguments:{cmd,cwd}}},{type:"tool/result",time:150+index*100,data:{callId:"call-"+index}}]);}
test("F02 main tool totals exclude active child session calls while retaining both timing sources",()=>{const root=reviewFixRoot(),main=join(root,"session-main"),child=join(root,"session-child");mkdirSync(main);mkdirSync(child);const mainPath=join(main,"session.v4.jsonl.zstd"),childPath=join(child,"session.v4.jsonl.zstd");const mainRows=[{type:"user/message",time:0,data:{source:{senderSessionId:"child"}}},...callsFor(["cat owned.md"],root)];const childRows=[...callsFor(["cat owned.md","cat owned.md"],root),{type:"tool/call",time:250,data:{name:"ask_user_question",callId:"child-ask"}},{type:"tool/result",time:350,data:{callId:"child-ask"}},{type:"tool/call",time:550,data:{name:"spawn_agent",callId:"child-spawn"}},{type:"tool/result",time:600,data:{callId:"child-spawn"}},{type:"tool/call",time:650,data:{name:"send_message",callId:"child-message"}},{type:"tool/result",time:700,data:{callId:"child-message"}}];for(const [dir,path,rows] of [[main,mainPath,mainRows],[child,childPath,childRows]]){const plain=join(dir,"input.jsonl");writeFileSync(plain,rows.map(row=>JSON.stringify(row)).join("\n"));const r=spawnSync("zstd",["-q","-f",plain,"-o",path],{encoding:"utf8"});expect(r.error).toBeUndefined();expect(r.status,r.stderr).toBe(0);}const value=runReviewLedger(mainPath);expect(value.sources).toHaveLength(2);expect(value.counts.tool_calls).toBe(1);expect(value.counts.tool_calls_by_name).toEqual({exec_command:1});expect(value.counts.main_self_execution).toBe(1);expect(value.accounted_ms).toBe(900);expect(value.accounting_ms).toEqual({platform_interrupt:0,human_wait:100,provider_activity:0,tool_subagent:500,unattributed:300});expect(value.counts.same_path_repeat_reads).toBe(2);expect(value.counts.subagent_dispatches).toBe(1);expect(value.counts.human_questions).toBe(1);expect(value.counts.messages.coordination).toBe(1);});
test("F03 absolute cat and sed executable paths count actual repeated source reads",()=>{const root=reviewFixRoot(),path=join(root,"session.jsonl");writeFileSync(path,callsFor(["/bin/cat owned.md","/usr/bin/sed -n '1,3p' owned.md"],root).map(row=>JSON.stringify(row)).join("\n"));const value=runReviewLedger(path);expect(value.counts.same_path_repeat_reads).toBe(1);expect(value.status).toBe("computed");expect(value.coverage_limits).toEqual([]);});
test.each(["env /bin/cat owned.md","sh -c 'cat owned.md'","cat \"$SOURCE_FILE\"","sed owned.md"])('F03 unparseable command form reports incomplete read coverage without inventing reads (%s)',cmd=>{const root=reviewFixRoot(),path=join(root,"session.jsonl");writeFileSync(path,callsFor([cmd,cmd],root).map(row=>JSON.stringify(row)).join("\n"));const value=runReviewLedger(path);expect(value.counts.same_path_repeat_reads).toBe(0);expect(value.status).toBe("inconclusive");expect(value.coverage_limits.length).toBeGreaterThan(0);});

// Actual DSH v4 envelope and JSON-string argument keys confirmed from the original session metadata.
function runDshCase(tools){const root=reviewFixRoot(),path=join(root,"dsh.jsonl");symlinkSync(join(root,"owned.md"),join(root,"alias.md"));const events=[{type:"session",version:4,id:"owned-session",createdAt:0,cwd:root,isSeeded:false,delegationDepth:0,agentPreset:"owned"}];tools(root).forEach(({name,arguments:args},index)=>{const callId="dsh-"+index;events.push({type:"tool/call",time:100+index*100,data:{turn:1,step:1,callId,name,arguments:typeof args==="string"?args:JSON.stringify(args)}},{type:"tool/result",time:150+index*100,data:{turn:1,step:1,message:{toolCallId:callId}}});});writeFileSync(path,events.map(row=>JSON.stringify(row)).join("\n"));return runReviewLedger(path);}
test("DSH bash metadata counts main execution and resolves relative literal reads from its own session cwd",()=>{const value=runDshCase(()=>[{name:"bash",arguments:{command:"cat ./owned.md",description:"owned read"}},{name:"bash",arguments:{command:"/usr/bin/sed -n '1,3p' alias.md",description:"owned read",timeoutMs:1000,run_in_background:false}}]);expect(value.counts.tool_calls_by_name).toEqual({bash:2});expect(value.counts.main_self_execution).toBe(2);expect(value.counts.same_path_repeat_reads).toBe(1);expect(value.status).toBe("computed");});
test("DSH subagent metadata counts named dispatch events without exposing prompt content",()=>{const value=runDshCase(()=>[{name:"subagent",arguments:{description:"owned dispatch",prompt:"opaque-prompt-must-not-be-output",run_in_background:true}}]);expect(value.counts.subagent_dispatches).toBe(1);expect(value.counts.main_self_execution).toBe(0);expect(JSON.stringify(value)).not.toContain("opaque-prompt-must-not-be-output");expect(value.status).toBe("computed");});
test("DSH read file_path metadata counts repeated physical paths regardless of offset and limit",()=>{const value=runDshCase(root=>[{name:"read",arguments:{file_path:join(root,"owned.md")}},{name:"read",arguments:{file_path:join(root,"alias.md"),offset:2,limit:5}}]);expect(value.counts.tool_calls_by_name).toEqual({read:2});expect(value.counts.same_path_repeat_reads).toBe(1);expect(value.counts.main_self_execution).toBe(0);expect(value.status).toBe("computed");});
test.each(["bash JSON unavailable","subagent fields incomplete","read file_path unavailable"])('DSH unrecognized argument metadata records incomplete coverage (%s)',mode=>{const value=runDshCase(()=>[mode==="bash JSON unavailable"?{name:"bash",arguments:"not-json"}:mode==="subagent fields incomplete"?{name:"subagent",arguments:{description:"owned dispatch"}}:{name:"read",arguments:{path:"owned.md"}}]);expect(value.status).toBe("inconclusive");expect(value.coverage_limits.length).toBeGreaterThan(0);expect(value.counts.same_path_repeat_reads).toBe(0);});

test("async human question accepted output is tool latency, not an answered waiting interval",()=>{const root=reviewFixRoot(),path=join(root,"codex.jsonl"),since=Date.parse("2026-10-04T23:31:36.121Z"),until=Date.parse("2026-10-04T23:31:36.209Z");writeFileSync(path,[{type:"session_meta",timestamp:new Date(since).toISOString(),payload:{id:"owned-codex",cwd:root}},{type:"response_item",timestamp:new Date(since).toISOString(),payload:{type:"function_call",name:"request_user_input_async",call_id:"owned-human",arguments:JSON.stringify({questions:[]})}},{type:"response_item",timestamp:new Date(until).toISOString(),payload:{type:"function_call_output",call_id:"owned-human",output:JSON.stringify({accepted:true})}}].map(row=>JSON.stringify(row)).join("\n"));const r=spawnSync(process.execPath,[join(import.meta.dirname,"card-09-session-ledger.mjs"),"--session",path,"--since",String(since),"--until",String(until)],{encoding:"utf8"});expect(r.status,r.stderr).toBe(0);const value=JSON.parse(r.stdout);expect(value.counts.human_questions).toBe(1);expect(value.counts.human_wait_ms).toBe(0);expect(value.accounting_ms).toEqual({platform_interrupt:0,human_wait:0,provider_activity:0,tool_subagent:88,unattributed:0});expect(value.status).toBe("inconclusive");expect(value.coverage_limits).toContain("async human response timing unavailable; immediate tool result is not an answer interval");});
