import {afterEach,expect,test} from "vitest";
import {randomUUID,createHash} from "node:crypto";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {createTask} from "../../runtime/task/task-handle.mjs";
import {recordSimpleReviewRequest} from "../../runtime/review/review-record-route.mjs";
import {runSimpleReview} from "../../skills/wh-review/scripts/simple-review-runner.mjs";
const roots=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const sha=b=>createHash("sha256").update(b).digest("hex");
const finding={severity:"minor",path:"materials/01-approved_spec.md",line:1,issue:"Owned preserved observation.",recommendation:"Keep the original fact.",evidence_kind:"direct",evidence:"owned current specification"};
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-preserve-")));roots.push(root);const repo=join(root,"repo");mkdirSync(repo);const task=await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:randomUUID(),created_at:new Date().toISOString(),target_repo_root:repo,activation_cohort:"post",record_model:"vnext-single-write",execution_mode:"per_invocation",issue_ids:[],inputs:{}}});return{root,task};}
function selection(){return{providers:["review/a"],provider_models:{"review/a":"model-a"},provider_identities:{"review/a":{source_id:"source-a",config_id:"config-a"}}};}
function member(extra={}){return{provider:"review/a",identity:{provider:"review/a",adapter:"review",model:"model-a",source_id:"source-a",config_id:"config-a"},status:"completed",error:null,output:JSON.stringify({findings:[finding]}),timing:{started_at_ms:1,completed_at_ms:2,duration_ms:1},usage:null,...extra};}
const request=()=>({stage:"build-code",review_scope:"phase",subject_kind:"phase",phase_id:"P2",surface:"document",materials:{approved_spec:"owned current specification",acceptance_criteria:"AC-60: preserve original member facts.",test_evidence:"owned case"}});
const deps=(f,client)=>({loadConfig:()=>({whReview:{},config:"unused",attachmentRoot:f.root,command:["unused"]}),resolveRoute:()=>({initial:["review/a"],mode:"single_round"}),selectProviders:selection,client,managedStatusPollMs:0});
async function record(f,client){const ref=await recordSimpleReviewRequest({taskDir:f.task.taskPath,request:request(),runRound:(input,options)=>runSimpleReview(input,{...deps(f,client),...options})});return JSON.parse(readFileSync(ref.path,"utf8"));}
test.each(["material mismatch","duplicate binding"])("round %s retains original completed member and raw bytes without authenticating its findings",async mode=>{const f=await fixture(),original=member();const value=await record(f,{runGroup:async({materials})=>({runtimeId:"owned-runtime",outcome:"completed",material_id:mode==="material mismatch"?"wrong-material":materials.materialId,providers:mode==="duplicate binding"?[original,member()]:[original]})});expect(value.status).toBe("unavailable");expect(value.error.code).toBe(mode==="material mismatch"?"REVIEW_MATERIAL_IDENTITY_MISMATCH":"PROVIDER_RESULT_INVALID");expect(value.provider_results[0]).toMatchObject({status:"completed",error:null,identity_authenticated:false});expect(value.findings).toEqual([]);const raw=value.provider_results[0].raw_output_ref;expect(raw).toBeTruthy();expect(sha(f.task.readRecordBytes(raw))).toBe(sha(original.output));});
test("a plain broker wait error preserves actually bound settled findings observed by the runner",async()=>{const f=await fixture();let seen=0;const value=await record(f,{startManaged:async({requestId,materials})=>({state:"running",request_id:requestId,runtime_id:"owned-runtime",material_id:materials.materialId,providers:{"review/a":member()}}),statusManaged:async({requestId,materials})=>{if(seen++===0)return{state:"running",request_id:requestId,runtime_id:"owned-runtime",material_id:materials.materialId,providers:{"review/a":member()}};throw Object.assign(new Error("observed transport interruption"),{code:"OWNED_OBSERVATION_INTERRUPTED"});}});expect(value.status).toBe("unavailable");expect(value.error.code).toBe("OWNED_OBSERVATION_INTERRUPTED");expect(value.provider_results[0]).toMatchObject({status:"completed",error:null,identity_authenticated:true});expect(value.findings).toMatchObject([{provider:"review/a",issue:finding.issue}]);expect(f.task.readRecordBytes(value.provider_results[0].raw_output_ref).toString()).toBe(member().output);});
test("record route preserves authenticated settled facts attached by the real runner boundary",async()=>{const f=await fixture();const recordRef=await recordSimpleReviewRequest({taskDir:f.task.taskPath,request:request(),runRound:async(_input,{onProviderOutput})=>{const raw=await onProviderOutput({provider:"review/a",output:member().output});throw Object.assign(new Error("round cannot finish"),{code:"OWNED_ROUND_ERROR",provider_results:[member({output:undefined,raw_output_ref:raw,identity_authenticated:true})],findings:[{...finding,provider:"review/a"}]});}});const value=JSON.parse(readFileSync(recordRef.path,"utf8"));expect(value).toMatchObject({status:"unavailable",error:{code:"OWNED_ROUND_ERROR"},provider_results:[{status:"completed",identity_authenticated:true}],findings:[{provider:"review/a",issue:finding.issue}]});});
