import {afterEach,expect,test,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {spawn} from "node:child_process";
import {existsSync,mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createTask} from "../../runtime/task/task-handle.mjs";
import {recordSimpleReviewRequest} from "../../runtime/review/review-record-route.mjs";
import {runSimpleReview} from "../../skills/wh-review/scripts/simple-review-runner.mjs";
const roots=[],children=[];afterEach(()=>{vi.useRealTimers();for(const child of children.splice(0))if(child.exitCode===null&&!child.killed)child.kill("SIGKILL");for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const finding={severity:"minor",path:"materials/01-approved_spec.md",line:1,issue:"Settled finding survives cancellation.",recommendation:"Retain the source.",evidence_kind:"direct",evidence:"owned current specification"};
const identity={provider:"review/a",adapter:"review",source_id:"source-a",config_id:"config-a",model:"model-a"};
const member=()=>({provider:"review/a",identity,status:"completed",error:null,output:JSON.stringify({findings:[finding]}),timing:{started_at_ms:1,completed_at_ms:2,duration_ms:1},usage:null});
const request=()=>({stage:"build-code",review_scope:"phase",subject_kind:"phase",phase_id:"P2",surface:"document",materials:{approved_spec:"owned current specification",acceptance_criteria:"AC-62: wait, stall, cancel and release.",test_evidence:"owned test"}});
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-stall-")));roots.push(root);mkdirSync(join(root,"repo"));const task=await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:randomUUID(),created_at:new Date().toISOString(),target_repo_root:join(root,"repo"),activation_cohort:"post",execution_mode:"per_invocation",record_model:"vnext-single-write",issue_ids:[],inputs:{}}});return{root,task};}
function dependencies(f,client,extra={}){return{loadConfig:()=>({whReview:{},config:"unused",attachmentRoot:f.root,command:["unused"]}),resolveRoute:()=>({initial:["review/a"],mode:"single_round"}),selectProviders:()=>({providers:["review/a"],provider_models:{"review/a":"model-a"},provider_identities:{"review/a":{source_id:"source-a",config_id:"config-a"}}}),client,managedStatusPollMs:10,maxPollMs:80,...extra};}
function broker({finish=20,progress=()=>1,controller=null,cancelAt=null,child=null}={}){let polls=0,cancels=0,cancelled=false;const times=[];let materialId,requestId,packetAtStart=null;const wire=()=>({state:"running",runtime_id:"owned-runtime",request_id:requestId,material_id:materialId,providers:{"review/a":{provider:"review/a",status:"running",last_progress_at_ms:progress(polls)}}});const client={startManaged:async input=>{materialId=input.materials.materialId;requestId=input.requestId;packetAtStart={root:input.materials.bundleRoot,exists:existsSync(input.materials.bundleRoot)};expect(packetAtStart.exists).toBe(true);return wire();},statusManaged:async()=>{times.push(Date.now());polls++;if(cancelAt===polls)controller.abort();return cancelled||polls===finish?{...wire(),state:"terminal",group:{runtime_id:"owned-runtime",outcome:"completed",material_id:materialId,providers:[member()]}}:wire();},cancelManaged:async()=>{cancels++;cancelled=true;if(child&&child.exitCode===null){const closed=new Promise(resolve=>child.once("close",resolve));child.kill("SIGTERM");await closed;}}};return{client,times,cancels:()=>cancels,packetAtStart:()=>packetAtStart};}
async function run(f,b,extra={}){const ref=await recordSimpleReviewRequest({taskDir:f.task.taskPath,request:request(),signal:extra.signal??null,runRound:(input,options)=>runSimpleReview(input,{...dependencies(f,b.client,extra),...options})});return JSON.parse(readFileSync(ref.path,"utf8"));}
test("twelve unchanged polls back off and notify once without cancellation, accepting delayed completion",async()=>{const f=await fixture();vi.useFakeTimers();const b=broker(),notices=[];const pending=run(f,b,{onManagedStall:event=>notices.push(event)});await vi.runAllTimersAsync();const value=await pending;const gaps=b.times.slice(1).map((t,i)=>t-b.times[i]);console.log("MANAGED_STALL_OBSERVED",JSON.stringify({polls:b.times.length,gaps,notices:notices.length,cancels:b.cancels()}));expect(gaps.slice(0,11)).toEqual(Array(11).fill(10));expect(gaps.some(g=>g>10)).toBe(true);expect(Math.max(...gaps)).toBeLessThanOrEqual(80);expect(notices).toHaveLength(1);expect(value.status).toBe("available");expect(b.cancels()).toBe(0);});
test("continuing progress retains the original polling frequency",async()=>{const f=await fixture();vi.useFakeTimers();const b=broker({progress:n=>n+1}),notices=[];const pending=run(f,b,{onManagedStall:event=>notices.push(event)});await vi.runAllTimersAsync();await pending;expect(b.times.slice(1).map((t,i)=>t-b.times[i])).toEqual(Array(19).fill(10));expect(notices).toEqual([]);});
test.each(["explicit cancel","stop waiting after stall"])("%s cancels once, reaps its child and packet, retaining settled findings",async mode=>{const f=await fixture(),controller=new AbortController();const child=spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"ignore"});children.push(child);vi.useFakeTimers();const b=broker({finish:100,controller,cancelAt:mode==="explicit cancel"?2:null,child}),notices=[];const pending=run(f,b,{signal:controller.signal,onManagedStall:event=>{notices.push(event);if(mode==="stop waiting after stall")controller.abort();}});await vi.runAllTimersAsync();const value=await pending;console.log("MANAGED_CANCEL_OBSERVED",JSON.stringify({mode,polls:b.times.length,cancel_count:b.cancels(),pid:child.pid,packet_before:b.packetAtStart().exists,packet_after:existsSync(b.packetAtStart().root),child_exit:child.exitCode,child_signal:child.signalCode}));expect(b.cancels()).toBe(1);expect(b.packetAtStart().exists).toBe(true);expect(existsSync(b.packetAtStart().root)).toBe(false);expect(child.exitCode!==null||child.signalCode!==null).toBe(true);expect(()=>process.kill(child.pid,0)).toThrow();expect(value).toMatchObject({status:"unavailable",error:{code:"REVIEW_CANCELLED"},findings:[{provider:"review/a",issue:finding.issue}]});const packetParent=join(f.root,".wh-review-packets");expect(!existsSync(packetParent)||requirePacketEmpty(packetParent)).toBe(true);if(mode==="stop waiting after stall")expect(notices).toHaveLength(1);});
function requirePacketEmpty(path){return process.getBuiltinModule("node:fs").readdirSync(path).length===0;}

test("progress after a stall resets cadence but a second stall does not repeat the request notice",async()=>{const f=await fixture();vi.useFakeTimers();const b=broker({finish:35,progress:n=>n<17?1:2}),notices=[];const pending=run(f,b,{onManagedStall:event=>notices.push(event)});await vi.runAllTimersAsync();const value=await pending;const gaps=b.times.slice(1).map((t,i)=>t-b.times[i]);console.log("MANAGED_STALL_RECOVERY_OBSERVED",JSON.stringify({polls:b.times.length,gaps,notices:notices.length}));expect(gaps[16]).toBe(10);expect(gaps.slice(16,27)).toEqual(Array(11).fill(10));expect(notices).toHaveLength(1);expect(value.status).toBe("available");expect(b.cancels()).toBe(0);});
