import {afterEach,expect,test} from "vitest";
import {createHash,randomUUID} from "node:crypto";
import {createTask} from "../../runtime/task/task-handle.mjs";
import {recordSimpleReviewRequest} from "../../runtime/review/review-record-route.mjs";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {buildReviewMaterials,PHASE_DIFF_INLINE_LIMIT_BYTES} from "../../skills/wh-review/scripts/review-materials.mjs";
import {runSimpleReview} from "../../skills/wh-review/scripts/simple-review-runner.mjs";
const roots=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const sha=b=>createHash("sha256").update(b).digest("hex");
function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"card09-navigation-")));roots.push(root);return root;}
function packet(root,diff,reverse=false){const diffPath=join(root,"source.diff");writeFileSync(diffPath,diff);let materials={approved_spec:"# Risks\nAC-61 checks the real consumer.\n",acceptance_criteria:"AC-61: complete navigation and bytes.",test_evidence:"owned case",phase_map:"# Consumer\nruntime/review/review-record-route.mjs\n"};if(reverse)materials=Object.fromEntries(Object.entries(materials).reverse());return buildReviewMaterials({stage:"build-code",reviewScope:"phase",phaseId:"P2",attachmentRoot:root,reviewDataRoot:root,source:{diffPath,diffBytes:Buffer.byteLength(diff),capturedHead:"a".repeat(40),baseCommit:"b".repeat(40)},materials});}
test.each([false,true])("short navigation resolves real manifest material paths regardless of caller order (%s)",reverse=>{const root=fixture(),diff="diff --git a/owned.mjs b/owned.mjs\n--- a/owned.mjs\n+++ b/owned.mjs\n@@ -1 +1 @@\n-old\n+new\n",p=packet(root,diff,reverse);try{const instructions=readFileSync(join(p.bundleRoot,"review-instructions.md"),"utf8"),nav=instructions.split("\n").slice(0,6).join("\n");expect(nav).toContain("先读");for(const suffix of ["approved_spec.md","phase_map.md"]){const entry=p.deliveryManifest.find(e=>e.path.endsWith(suffix));expect(entry).toBeTruthy();expect(nav).toContain(entry.path);}expect(nav).toContain("requirements/acceptance_criteria.md");expect(nav).toContain("changes.diff");for(const path of [...nav.matchAll(/\x60([^\x60]+)\x60/g)].map(m=>m[1])){const entry=p.deliveryManifest.find(e=>e.path===path);expect(entry,path).toBeTruthy();expect(sha(readFileSync(join(p.bundleRoot,path)))).toBe(entry.sha256);}}finally{p.dispose();}});
test("a diff larger than 288 KiB remains byte complete with a real shard index navigation",()=>{const root=fixture(),body="+const value = '"+"x".repeat(PHASE_DIFF_INLINE_LIMIT_BYTES+4096)+"';\n",diff="diff --git a/owned.mjs b/owned.mjs\n--- a/owned.mjs\n+++ b/owned.mjs\n@@ -1 +1 @@\n-old\n"+body,p=packet(root,diff);try{const nav=readFileSync(join(p.bundleRoot,"review-instructions.md"),"utf8").split("\n").slice(0,6).join("\n");expect(nav).toContain("diff-index.json");const index=JSON.parse(readFileSync(join(p.bundleRoot,"diff-index.json"),"utf8"));const shards=index.changes.flatMap(c=>c.shards);const full=Buffer.concat(shards.map(s=>readFileSync(join(p.bundleRoot,s.ref))));expect(full).toEqual(Buffer.from(diff));}finally{p.dispose();}});
test.each(["missing material","route conflict","wrong lifecycle","invalid parse"])("controllable %s is exposed before semantic success",async mode=>{const root=fixture();let dispatch=0;const input={stage:"build-code",review_scope:"phase",phase_id:"P2",subject_kind:"phase",materials:{approved_spec:"owned",acceptance_criteria:"AC-61: reject controllable errors.",test_evidence:"owned"}};const client={runGroup:async()=>{dispatch++;return{runtimeId:"owned",outcome:"completed",providers:[]};}};const dependencies={loadConfig:()=>({whReview:{},config:"unused",attachmentRoot:root,command:["unused"]}),resolveRoute:()=>({initial:["review/a"],mode:"single_round"}),selectProviders:()=>({providers:["review/a"]}),client};if(mode==="missing material")delete input.materials.approved_spec;if(mode==="route conflict")dependencies.resolveRoute=()=>{throw new Error("conflicting source configuration");};if(mode==="wrong lifecycle")input.review_scope="wrong";if(mode==="invalid parse")input.materials.approved_spec=Buffer.from([0xff]);if(mode==="wrong lifecycle"){const repo=join(root,"repo");mkdirSync(repo);const task=await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:randomUUID(),created_at:new Date().toISOString(),target_repo_root:repo,activation_cohort:"post",record_model:"vnext-single-write",execution_mode:"per_invocation",issue_ids:[],inputs:{}}});let observed;try{await recordSimpleReviewRequest({taskDir:task.taskPath,request:input,runRound:async()=>{dispatch++;}});}catch(error){observed=error;}expect(observed).toMatchObject({code:"REVIEW_IDENTITY_INVALID",preflight_protocol:true,diagnostic:{field:"stage/review_track/review_kind/review_scope"}});expect(observed.message).toContain("build-code requires phase review_scope");expect(dispatch).toBe(0);return;}const value=await runSimpleReview(input,dependencies);expect(value.status).toBe("unavailable");expect(value.preflight_diagnostic??value.error?.diagnostic).toBeTruthy();expect(value.dispatch_state).toBe("blocked_before_dispatch");expect(dispatch).toBe(0);});
