// Current code-review publication is the single request/ordinary-result writer.
// Public OCR route/real source-anchor checks are exercised by current route
// tests; no retired DSH caller-authored-result, snapshot or receipt authority.
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createTask } from "../../runtime/task/task-handle.mjs";
import { recordSimpleReviewRequest } from "../../runtime/review/review-record-route.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"current-code-publication-")));roots.push(root);const repo=join(root,"metadata-repo");mkdirSync(repo);return await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:randomUUID(),created_at:"2026-10-03T00:00:00Z",target_repo_root:repo,activation_cohort:"post",record_model:"vnext-single-write",execution_mode:"per_invocation",issue_ids:[],inputs:{}}});}
const request={stage:"verify-code",surface:"code",subject_kind:"worktree",subject:{scope:"owned submitted current code"},materials:{implementation:"review subject"}};
const provider=()=>({provider:"codex/owned",status:"completed",identity:{provider:"codex/owned",adapter:"codex",source_id:"owned/source",config_id:"owned/config",model:"owned-model"},output:JSON.stringify({findings:[]}),error:null,timing:{started_at_ms:1,completed_at_ms:2,duration_ms:1},usage:null,evidence_anchor_valid:[]});
const finding={severity:"major",path:"README.md",line:1,issue:"The observed branch contradicts the current implementation.",recommendation:"Make the implementation follow the documented behavior.",root_cause:"The implementation omits the required condition.",evidence_kind:"direct",evidence:"review subject",provider:"codex/owned"};
const semantic=()=>({status:"available",outcome:"completed",dispatch_state:"dispatched",provider_results:[provider()],findings:[]});
async function publish(task,result){const ref=await recordSimpleReviewRequest({taskDir:task.taskPath,request,runRound:async()=>result});return{ref,value:JSON.parse(task.readRecord(ref.result_ref))};}
function jsonFiles(task){const dir=join(task.taskPath,"quality","reviews");return existsSync(dir)?readdirSync(dir).filter(x=>x.endsWith(".json")):[];}
describe("current ordinary code-review publication",()=>{
 it("stores a completed zero-finding observation with provider provenance and original output",async()=>{const task=await fixture(),{ref,value}=await publish(task,semantic());expect(ref.status).toBe("available");expect(value).toMatchObject({task_id:task.identity.taskId,stage:"verify-code",status:"available",authoritative:false,findings:[],request:{subject:request.subject}});expect(value.provider_results[0].identity).toEqual(provider().identity);expect(readFileSync(value.provider_results[0].output_ref,"utf8")).toBe(provider().output);expect(value).not.toHaveProperty("attempt_ref");expect(value).not.toHaveProperty("snapshot_tree");});
 it("preserves serious finding evidence, root cause, original provider and submitted anchor facts",async()=>{const task=await fixture(),p={...provider(),evidence_anchor_valid:[true],output:JSON.stringify({findings:[finding]})},{value}=await publish(task,{...semantic(),provider_results:[p],findings:[finding]});expect(value.findings).toEqual([finding]);expect(value.provider_results[0].evidence_anchor_valid).toEqual([true]);expect(JSON.parse(readFileSync(value.provider_results[0].output_ref,"utf8"))).toEqual({findings:[finding]});expect(value.authoritative).toBe(false);});
 it("preserves a minor observation without inventing a source-line anchor or a completion decision",async()=>{const task=await fixture(),minor={severity:"minor",path:"README.md",issue:"wording can be clearer",recommendation:"use a shorter sentence",provider:"codex/owned"},{value}=await publish(task,{...semantic(),provider_results:[{...provider(),evidence_anchor_valid:[false]}],findings:[minor]});expect(value.findings).toEqual([minor]);expect(value.findings[0]).not.toHaveProperty("line");expect(value.provider_results[0].evidence_anchor_valid).toEqual([false]);expect(value.authoritative).toBe(false);});
 it.each([null,{status:"unknown"},{status:"available",provider_results:[],findings:[]},{status:"available",provider_results:[provider()],findings:null}])("rejects malformed semantic publisher output without a canonical JSON result: %j",async result=>{const task=await fixture();await expect(publish(task,result)).rejects.toThrow();expect(jsonFiles(task)).toEqual([]);});
 it.each([{root_cause:undefined},{evidence_kind:undefined},{evidence:""},{evidence_kind:"unverified"},{line:0},{line:-1},{path:"/owned-absolute.txt"},{path:"file://owned/source"},{path:"owned\\source"}])("rejects invalid ordinary serious-finding shape %j",async change=>{const task=await fixture();await expect(publish(task,{...semantic(),findings:[{...finding,...change}]})).rejects.toMatchObject({code:"OUTPUT_INVALID"});expect(jsonFiles(task)).toEqual([]);});
 it("keeps an actual submitted anchor failure unavailable with its raw output and typed error",async()=>{const task=await fixture(),failed={...provider(),status:"failed",error:{code:"OUTPUT_INVALID",message:"submitted provider source anchor invalid"},evidence_anchor_valid:[false],output:JSON.stringify({findings:[{...finding,evidence:"unanchored observed text"}]})},{value}=await publish(task,{status:"unavailable",outcome:"unavailable",dispatch_state:"sent_unparsed",provider_results:[failed],findings:[]});expect(value.status).toBe("unavailable");expect(value.findings).toEqual([]);expect(value.provider_results[0]).toMatchObject({status:"failed",error:{code:"OUTPUT_INVALID"},evidence_anchor_valid:[false]});expect(readFileSync(value.provider_results[0].output_ref,"utf8")).toBe(failed.output);});
 it("rejects a reported stage identity mismatch instead of relabelling the submitted scope",async()=>{const task=await fixture();await expect(publish(task,{...semantic(),stage:"build-code"})).rejects.toMatchObject({code:"REVIEW_SUBJECT_MISMATCH"});expect(jsonFiles(task)).toEqual([]);});
 it("preserves extra ordinary finding facts without reviving snapshot certification",async()=>{const task=await fixture(),reported={...finding,confidence:"high"},{value}=await publish(task,{...semantic(),snapshot_tree:"retired-unused",material_revision:"retired-unused",findings:[reported]});expect(value.findings).toEqual([reported]);expect(value).not.toHaveProperty("snapshot_tree");expect(value).not.toHaveProperty("material_revision");});
});
