// Current canonical ordinary request/result producer. No kernel, pair/role
// authentication, hash freshness, retry authority or receipt readback machine.
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createTask } from "../../runtime/task/task-handle.mjs";
import { recordSimpleReviewRequest } from "../../runtime/review/review-record-route.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"ordinary-review-record-")));roots.push(root);const repo=join(root,"metadata-repo");mkdirSync(repo);const task=await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:randomUUID(),created_at:"2026-10-03T00:00:00Z",target_repo_root:repo,activation_cohort:"post",record_model:"vnext-single-write",execution_mode:"per_invocation",issue_ids:[],inputs:{}}});return{root,task};}
const request=(phase="P1")=>({stage:"build-code",review_scope:"phase",phase_id:phase,subject_kind:"phase",surface:"code",subject:{files:["README.md"]},materials:{approved_spec:"owned ordinary current specification"}});
const member=(provider="codex/owned",extra={})=>({provider,status:"completed",identity:{provider,adapter:provider.split('/')[0],source_id:`${provider}-source`,config_id:`${provider}-config`,model:"owned-model"},error:null,timing:{started_at_ms:1,completed_at_ms:2,duration_ms:1},usage:null,evidence_anchor_valid:[],...extra});
const result=(extra={})=>({status:"unavailable",outcome:"unavailable",dispatch_state:"unknown",provider_results:[],findings:[],...extra});
const finding=(provider="codex/owned")=>({provider,severity:"major",path:"README.md",line:1,issue:"current branch has a defect",recommendation:"repair the branch",root_cause:"missing required branch",evidence_kind:"direct",evidence:"owned observed line"});
async function record(f,runRound,input=request(),extra={}){const ref=await recordSimpleReviewRequest({taskDir:f.task.taskPath,request:input,runRound,...extra});return{ref,value:JSON.parse(f.task.readRecord(ref.result_ref)),bytes:f.task.readRecordBytes(ref.result_ref)};}
function results(f){const dir=join(f.task.taskPath,"quality","reviews");return existsSync(dir)?readdirSync(dir).filter(x=>x.endsWith(".json")):[];}
describe("ordinary review request/result lifecycle",()=>{
 it("preserves all submitted semantic members and duplicate claims with their actual provider rather than certifying corroboration",async()=>{const f=await fixture(),providers=[member(),member("other/owned")],claims=[finding(),finding("other/owned"),{...finding(),line:2,issue:"unique claim"}],{value}=await record(f,async()=>result({status:"available-with-failures",outcome:"partial",dispatch_state:"dispatched",provider_results:[...providers,member("third/owned",{status:"failed",error:{code:"OWNED_FAILED",message:"failed sibling"}})],findings:claims}));expect(value.findings).toEqual(claims);expect(value.provider_results.map(p=>p.status)).toEqual(["completed","completed","failed"]);expect(value.provider_results[2].error.code).toBe("OWNED_FAILED");expect(value.authoritative).toBe(false);expect(value).not.toHaveProperty("coverage");});
 it("keeps process/parse/health/error/null usage as observed facts without inventing fallback outcomes",async()=>{const f=await fixture(),p=member("codex/owned",{status:"failed",process_outcome:null,output_parse:null,usage:null,health:{provider:"codex/owned",status:"failed",stdout_bytes:7},error:{code:"PROCESS_TIMEOUT",message:"owned fixed deadline",cause_code:"OWNED_CAUSE"},raw_output:"owned original error stream"}),{value}=await record(f,async()=>result({provider_results:[p],error:{code:"PROCESS_TIMEOUT",message:"owned fixed deadline",cause_code:"OWNED_CAUSE"}}));expect(value.provider_results[0]).toMatchObject({process_outcome:null,output_parse:null,usage:null,health:p.health,error:p.error});expect(value.error).toEqual(p.error);expect(f.task.readRecord(value.provider_results[0].raw_output_ref)).toBe(p.raw_output);expect(value.status).toBe("unavailable");});
 it("stores raw nonUTF8 provider output as one original and carries the reference into the ordinary result",async()=>{const f=await fixture(),raw=Buffer.from([0x66,0x00,0xff,0x80]);let ref;const saved=await record(f,async(_input,options)=>{ref=await options.onProviderOutput({provider:"codex/owned",output:raw});return result({provider_results:[member("codex/owned",{status:"failed",raw_output_ref:ref,error:{code:"OUTPUT_INVALID",message:"owned invalid bytes"}})]});});expect(f.task.readRecordBytes(ref)).toEqual(raw);expect(saved.value.provider_results[0].raw_output_ref).toBe(ref);expect(readdirSync(join(f.task.taskPath,"quality","reviews")).filter(n=>n.endsWith(".output"))).toHaveLength(1);});
 it("keeps an unavailable valid partial finding and its provider source, leaving the required minimum unchanged",async()=>{const f=await fixture(),partial=finding(),{value}=await record(f,async()=>result({minimum_heterologous:2,provider_results:[member()],findings:[partial],error:{code:"REVIEW_MINIMUM_UNMET",message:"one source only"}}));expect(value).toMatchObject({status:"unavailable",minimum_heterologous:2,error:{code:"REVIEW_MINIMUM_UNMET"},findings:[partial],authoritative:false});});
 it.each(["stage","review_track","review_scope","phase_id","subject_kind","surface"])("rejects a returned %s mismatch rather than relabelling the subject",async key=>{const f=await fixture();await expect(record(f,async()=>result({[key]:"wrong"}))).rejects.toMatchObject({code:"REVIEW_SUBJECT_MISMATCH"});expect(results(f)).toEqual([]);});
 it.each([{stage:"build-code",review_scope:"phase",reviewScope:"integration",phase_id:"P1"},{stage:"make-decision",review_track:"direction",reviewTrack:"detail"},{stage:"verify-code",review_scope:"phase"},{stage:"build-code",phase_id:"not-a-phase"}])("rejects an invalid request identity before calling a runner %j",async input=>{const f=await fixture();let calls=0;await expect(record(f,async()=>{calls++;return result();},{...input,materials:{approved_spec:"owned"}})).rejects.toThrow();expect(calls).toBe(0);expect(results(f)).toEqual([]);});
 it("preserves concrete phase and mini-task identities from the submitted current tuple",async()=>{const f=await fixture();for(const input of [request("P1"),request("P2"),{...request("P2"),review_scope:undefined,review_kind:"mini_task.implementation"}]){const {value}=await record(f,async received=>{expect(received.phase_id).toBe(input.phase_id);return result();},input);expect(value.phase_id).toBe(input.phase_id);expect(value.review_scope).toBe("phase");expect(value.request.subject).toEqual(input.subject);expect(value.review_kind).toBe(input.review_kind??null);}});
 it("appends each explicit request without retry/head/reuse gates and preserves prior original bytes",async()=>{const f=await fixture();let calls=0;const run=async()=>{calls++;return result();};const first=await record(f,run),second=await record(f,run,{...request(),reason:"another explicit request"}),third=await record(f,run,{...request(),materials:{approved_spec:"changed ordinary material"}});expect(calls).toBe(3);expect(new Set([first.ref.result_ref,second.ref.result_ref,third.ref.result_ref]).size).toBe(3);expect(f.task.readRecordBytes(first.ref.result_ref)).toEqual(first.bytes);});
 it("serializes concurrent ordinary requests and retains every original result",async()=>{const f=await fixture(),trace=[];let number=0;const run=async()=>{const id=++number;trace.push(`start${id}`);await new Promise(r=>setTimeout(r,20));trace.push(`end${id}`);return result();};const records=await Promise.all([record(f,run),record(f,run)]);expect(trace).toEqual(["start1","end1","start2","end2"]);expect(records[0].ref.result_ref).not.toBe(records[1].ref.result_ref);expect(results(f)).toHaveLength(2);});
 it("does not call an already cancelled runner and publishes no fake result",async()=>{const f=await fixture(),controller=new AbortController();controller.abort();let calls=0;await expect(record(f,async()=>{calls++;return result();},request(),{signal:controller.signal})).rejects.toMatchObject({code:"REVIEW_CANCELLED"});expect(calls).toBe(0);expect(results(f)).toEqual([]);});
 it("waits for a live cancelled round to settle, retains its original facts and releases the lock only after cleanup",async()=>{const f=await fixture(),controller=new AbortController();let started,finish;const ready=new Promise(r=>started=r),cleanup=new Promise(r=>finish=r),trace=[];const first=record(f,async(_input,{signal})=>{trace.push("first-start");started();await cleanup;expect(signal.aborted).toBe(true);trace.push("first-cleaned");return result({provider_results:[member("codex/owned",{status:"cancelled",error:{code:"OCR_PROVIDER_CANCELLED",message:"owned cancellation"}})]});},request(),{signal:controller.signal});await ready;controller.abort();const second=record(f,async()=>{trace.push("second-start");return result();});await new Promise(r=>setTimeout(r,20));expect(trace).toEqual(["first-start"]);finish();const [a,b]=await Promise.all([first,second]);expect(trace).toEqual(["first-start","first-cleaned","second-start"]);expect(a.value).toMatchObject({status:"unavailable",error:{code:"REVIEW_CANCELLED"},provider_results:[{status:"cancelled",error:{code:"OCR_PROVIDER_CANCELLED"}}]});expect(b.value.status).toBe("unavailable");});
 it("records a typed throwing runner failure with unknown dispatch instead of inferring send from invocation",async()=>{const f=await fixture(),{value}=await record(f,async()=>{throw Object.assign(new Error("owned launch failure"),{code:"BROKER_SPAWN_FAILED"});});expect(value).toMatchObject({status:"unavailable",dispatch_state:"unknown",provider_results:[],findings:[],error:{code:"BROKER_SPAWN_FAILED",message:"owned launch failure"}});});
 it("keeps malformed foreign history passive and stores a new current result without a namespace gate",async()=>{const f=await fixture(),dir=join(f.task.taskPath,"quality","reviews","results");mkdirSync(dir,{recursive:true});const raw=Buffer.from('{"old-pair":');writeFileSync(join(dir,"old.json"),raw);const {value}=await record(f,async()=>result());expect(value.status).toBe("unavailable");expect(readFileSync(join(dir,"old.json"))).toEqual(raw);});
});
