// Reopen the same ordinary task; no recovery/successor/continuation object.
import {afterEach,expect,it} from "vitest";import {execFileSync,spawnSync}from"node:child_process";import{mkdirSync,mkdtempSync,readFileSync,readdirSync,realpathSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{fileURLToPath}from"node:url";
import{bootstrapTask}from"../../tools/cli/task-bootstrap.mjs";import{openTask}from"../../runtime/task/task-handle.mjs";import{openCurrentTaskWorkspace}from"../../runtime/task/workspace.mjs";import{ArtifactDir}from"../../runtime/evidence/artifact-dir.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
it("reopens one actual task and preserves original facts while continuing through public status and draft",async()=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),"same-task-current-")));roots.push(root);const repo=join(root,"repo"),storage=join(root,"storage"),home=join(root,"home");for(const p of[repo,storage,home])mkdirSync(p);
 const env={...process.env,HOME:home,WORKFLOWHUB_TASK_DIR:storage};for(const k of Object.keys(env))if(k.startsWith("GIT_"))delete env[k];const git=args=>execFileSync("git",args,{cwd:repo,env,stdio:["ignore","pipe","pipe"]});git(["init","-q","-b","main"]);git(["config","user.name","Owned same task"]);git(["config","user.email","owned@test.invalid"]);writeFileSync(join(repo,"README.md"),"owned\n");git(["add","README.md"]);git(["commit","-qm","base"]);
 const taskId="interrupted-same-task",first=await bootstrapTask({project:"WorkflowHub",task:taskId,"target-repo":repo},{env,home}),taskPath=first.task_path,wt=first.workspace.worktree_root;
 const materialRoot=join(wt,"specs",taskId);mkdirSync(materialRoot,{recursive:true});writeFileSync(join(materialRoot,"decision-log.md"),"# Current decision\nOriginal user need.\n");writeFileSync(join(materialRoot,"spec.md"),"# Original specification\n");
 const facts=Buffer.from(JSON.stringify({task_id:taskId,stage:"build-code",status:"unknown",snapshot_tree:"passive-history"})+"\n");writeFileSync(join(taskPath,"facts.jsonl"),facts);const manifest=readFileSync(join(taskPath,"task.json"));
 const reopened=openTask(taskPath,{projectName:"WorkflowHub",taskId}),workspace=await openCurrentTaskWorkspace(reopened),artifacts=ArtifactDir.open(workspace.worktreeRoot,reopened);expect(artifacts.read("spec.md")).toBe("# Original specification\n");expect(workspace.worktreeRoot).toBe(wt);
 const cli=fileURLToPath(new URL("../../tools/cli/stage-runtime.mjs",import.meta.url));const call=args=>spawnSync(process.execPath,[cli,...args],{cwd:wt,env,encoding:"utf8",timeout:10000});const common=["--stage=build-plan","--project=WorkflowHub",`--task=${taskId}`,`--task-path=${taskPath}`];
 const status=call(["status","--action=begin",...common]);expect(status.status,status.stderr).toBe(0);expect(JSON.parse(status.stdout)).toMatchObject({task_id:taskId,quality_status:"unknown"});
 const input=join(root,"draft.md");writeFileSync(input,"# Continued specification\nSame ordinary task.\n");const draft=call(["run","--action=draft",...common,"--name=spec.md",`--input=${input}`]);expect(draft.status,draft.stderr).toBe(0);expect(readFileSync(join(materialRoot,"spec.md"))).toEqual(readFileSync(input));expect(readFileSync(join(taskPath,"task.json"))).toEqual(manifest);expect(readFileSync(join(taskPath,"facts.jsonl"))).toEqual(facts);
 expect(readdirSync(join(storage,"Projects","WorkflowHub","tasks"))).toEqual([taskId]);expect(readdirSync(taskPath).some(name=>/recovery|successor|rebind|continuation/i.test(name))).toBe(false);
});
