// Real owned A progress/target merge remains; old resume object/certification graph retires.
import{afterEach,expect,it}from"vitest";import{execFileSync,spawnSync}from"node:child_process";import{existsSync,mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{bootstrapTask}from"../../tools/cli/task-bootstrap.mjs";
import{evaluateMiniTaskScope,prepareAResumePlan,confirmAResumePlan,authorizeAResumePlan,resumeTaskA}from"../../skills/mini-task/scripts/mini-task-runner.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
async function fixture(conflict=false){const root=realpathSync(mkdtempSync(join(tmpdir(),"owned-a-progress-")));roots.push(root);const repo=join(root,"repo"),storage=join(root,"storage"),home=join(root,"home");for(const d of[repo,storage,home])mkdirSync(d);const env={...process.env,HOME:home,WORKFLOWHUB_TASK_DIR:storage};for(const k of Object.keys(env))if(k.startsWith("GIT_"))delete env[k];const git=(cwd,args,optional=false)=>{const r=spawnSync("git",args,{cwd,env,encoding:"utf8"});if(optional)return r;expect(r.status,r.stderr).toBe(0);return r.stdout.trim();};git(repo,["init","-q","-b","main"]);git(repo,["config","user.name","Owned A"]);git(repo,["config","user.email","owned@test.invalid"]);writeFileSync(join(repo,"shared.txt"),"base\n");git(repo,["add","shared.txt"]);git(repo,["commit","-qm","base"]);const b=await bootstrapTask({project:"workflowhub",task:"owned-a","target-repo":repo},{env,home}),wt=b.workspace.worktree_root;writeFileSync(join(repo,"mini.txt"),"mini target\n");if(conflict)writeFileSync(join(repo,"shared.txt"),"target conflicting change\n");git(repo,["add","."]);git(repo,["commit","-qm","mini target"]);return{repo,wt,taskDir:b.task_path,git,targetOid:git(repo,["rev-parse","HEAD"])};}
async function approve(f,p){const c=await confirmAResumePlan({taskDir:f.taskDir,planRef:p.plan_ref,replyText:"Controlled approval for this owned progress and target merge."});await authorizeAResumePlan({taskDir:f.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});return c;}
it("pauses scope expansion for an explicit user route choice",()=>{expect(evaluateMiniTaskScope({major_architecture:true,user_requested:true})).toMatchObject({status:"paused",choices:["shrink-mini-task","create-ordinary-five-stage-task"]});});
it("preserves dirty A progress, merges the explicit target and records rerun facts",async()=>{const f=await fixture(),before=f.git(f.wt,["rev-parse","HEAD"]);writeFileSync(join(f.wt,"a-progress.txt"),"A progress\n");const p=await prepareAResumePlan({taskDir:f.taskDir,targetOid:f.targetOid,originalStage:"build-plan"});expect(p.plan.steps).toEqual(["commit","merge"]);const c=await approve(f,p),r=await resumeTaskA({taskDir:f.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});expect(r.status).toBe("completed");expect(r.next_action).toBe("rerun_original_stage");expect(f.git(f.wt,["rev-parse","HEAD"])).not.toBe(before);expect(f.git(f.wt,["rev-parse","HEAD^2"])).toBe(f.targetOid);expect(readFileSync(join(f.wt,"a-progress.txt"),"utf8")).toBe("A progress\n");expect(readFileSync(join(f.wt,"mini.txt"),"utf8")).toBe("mini target\n");expect(JSON.parse(readFileSync(r.evidence_ref,"utf8"))).toMatchObject({status:"completed",next_action:"rerun_original_stage"});});
it("aborts an actual merge conflict, keeps A progress and never records false completion",async()=>{const f=await fixture(true);writeFileSync(join(f.wt,"shared.txt"),"A conflicting progress\n");const p=await prepareAResumePlan({taskDir:f.taskDir,targetOid:f.targetOid}),c=await approve(f,p),r=await resumeTaskA({taskDir:f.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});expect(r.status).toBe("failed");expect(f.git(f.wt,["rev-parse","--verify","MERGE_HEAD"],true).status).not.toBe(0);expect(f.git(f.wt,["status","--porcelain"])).toBe("");expect(readFileSync(join(f.wt,"shared.txt"),"utf8")).toBe("A conflicting progress\n");});
it("does not invent a progress commit for a clean A workspace",async()=>{const f=await fixture(),p=await prepareAResumePlan({taskDir:f.taskDir,targetOid:f.targetOid});expect(p.plan.steps).toEqual(["merge"]);const c=await approve(f,p),r=await resumeTaskA({taskDir:f.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});expect(r.status).toBe("completed");expect(f.git(f.wt,["rev-parse","HEAD^1"])).toBe(p.plan.source.head);});
