import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import{runPrivateTargetedCapture}from"../../workflows/build-code/targeted-capture.mjs";import{runTargetedCases}from"../../workflows/build-code/targeted-runner.mjs";
import{lstatSync}from"node:fs";
function captureFixture(){const r=root(),records=join(r,"records");mkdirSync(records);return{r,records};}
const cap=(f,slug,code,extra={})=>runPrivateTargetedCapture({cwd:f.r,recordDir:f.records,slug,argv:[process.execPath,"-e",code],...extra});
function targetFixture(){const f=captureFixture();mkdirSync(join(f.r,"tests"));const marker=join(f.r,"ran.marker"),target="tests/effect.test.mjs";writeFileSync(join(f.r,target),`import{test}from"node:test";import{writeFileSync}from"node:fs";test("owned effect",()=>writeFileSync(${JSON.stringify(marker)},"actual"));\n`);return{...f,target,marker};}
const selection=(target)=>({status:"selected",cases:[{id:"OWNED",execution:{target,expected_test_identity:"owned effect",runner:"node:test"}}]});
const run=(f,s=selection(f.target))=>runTargetedCases({workspaceRoot:f.r,selection:s,runner:{executable:process.execPath,fixedArgs:["--test","--test-reporter=tap"]}});
describe("targeted command facts and owned process protection",()=>{
 it("preserves first pass and second real failure stdout/stderr in distinct immutable originals",async()=>{const f=captureFixture(),first=await cap(f,"first",String.raw`process.stdout.write("first-pass\n");`),before=readFileSync(first.output_ref),second=await cap(f,"second",String.raw`process.stdout.write("second-fail\n");process.stderr.write("actual-stderr\n");process.exit(7);`);expect(first.exit_code).toBe(0);expect(second.exit_code).toBe(7);expect(readFileSync(second.output_ref,"utf8")).toContain("second-fail");expect(readFileSync(second.output_ref,"utf8")).toContain("actual-stderr");expect(readFileSync(first.output_ref)).toEqual(before);expect(first.output_ref).not.toBe(second.output_ref);expect(JSON.parse(readFileSync(second.receipt_ref))).toMatchObject({exit_code:7,output_ref:second.output_ref});});
 it("runs the fresh selected child and retains raw TAP and actual effect without receipt certification",async()=>{const f=targetFixture();expect(existsSync(f.marker)).toBe(false);const result=await run(f);expect(result.status).toBe("completed");expect(readFileSync(f.marker,"utf8")).toBe("actual");expect(result.execution).toMatchObject({exit_code:0,source:"direct_runner",canonical_receipt:false});expect(result.execution.raw_output).toContain("ok 1 - owned effect");expect(result.observations).toMatchObject([{case_id:"OWNED",status:"passed",canonical_receipt:false}]);});
 it.each(["../outside.test.mjs","/tmp/outside.test.mjs","tests/missing.test.mjs"])("rejects %s before a target starts",async target=>{const f=targetFixture(),result=await run(f,selection(target));expect(result.status).toBe("unavailable");expect(result.reason).toBe(target.includes("missing")?"missing_target":"unsafe_target");expect(existsSync(f.marker)).toBe(false);});
 it("rejects a later unsafe target before the earlier safe child can run",async()=>{const f=targetFixture(),s=selection(f.target);s.cases.push({id:"UNSAFE",execution:{target:"../outside.test.mjs",expected_test_identity:"outside"}});expect(await run(f,s)).toMatchObject({status:"unavailable",reason:"unsafe_target",observations:[]});expect(existsSync(f.marker)).toBe(false);});
 it("does not execute unknown selection, duplicate case identities or shared target assignments",async()=>{const f=targetFixture();expect(await run(f,{status:"unavailable",cases:[]})).toMatchObject({reason:"unknown_change_scope"});const s=selection(f.target);s.cases.push({...s.cases[0]});expect(await run(f,s)).toMatchObject({reason:"duplicate_case_id"});s.cases[1].id="OTHER";expect(await run(f,s)).toMatchObject({reason:"reporter_identity_mismatch"});expect(existsSync(f.marker)).toBe(false);});
 it("rejects a target symlink before running a declared test",async()=>{const f=targetFixture(),outside=join(f.r,"outside.test.mjs");writeFileSync(outside,'process.exit(99);');rmSync(join(f.r,f.target));symlinkSync(outside,join(f.r,f.target));expect(await run(f)).toMatchObject({status:"unavailable",reason:"unsafe_target"});expect(existsSync(f.marker)).toBe(false);});
 it("uses the explicit timeout to stop a delayed side effect and preserves partial raw",async()=>{const f=captureFixture(),late=join(f.r,"late.marker"),result=await cap(f,"timeout",`process.stdout.write("started");setTimeout(()=>require("node:fs").writeFileSync(${JSON.stringify(late)},"late"),5000);`,{timeoutMs:400});expect(result).toMatchObject({exit_code:124,timed_out:true,cancelled:false});expect(readFileSync(result.output_ref,"utf8")).toContain("started");expect(existsSync(late)).toBe(false);});
 it("cancels an actually started owned child and drains its output before return",async()=>{const f=captureFixture(),marker=join(f.r,"child.json"),controller=new AbortController();const promise=cap(f,"cancel",`process.stdout.write("alive",()=>{require("node:fs").writeFileSync(${JSON.stringify(marker)},JSON.stringify({pid:process.pid}));setInterval(()=>{},1000);});`,{signal:controller.signal,timeoutMs:3000}).then(value=>({ok:true,value}),error=>({ok:false,error}));const deadline=Date.now()+2000;while(!existsSync(marker)&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));try{expect(existsSync(marker)).toBe(true);const pid=JSON.parse(readFileSync(marker)).pid;controller.abort(Object.assign(new Error("owned cancel"),{code:"REVIEW_CANCELLED"}));const observed=await promise;expect(observed.ok).toBe(false);expect(observed.error.code).toBe("ABORT_ERR");const result=JSON.parse(readFileSync(observed.error.receipt_ref));expect(result.cancelled).toBe(true);expect(result.exit_code).toBe(130);expect(readFileSync(result.output_ref,"utf8")).toContain("alive");expect(()=>process.kill(pid,0)).toThrow();}finally{controller.abort();await promise.catch(()=>{});}});
 it("bounds oversized raw output without silently claiming the full stream",async()=>{const f=captureFixture(),result=await cap(f,"large",'process.stdout.write("x".repeat(9*1024*1024));');expect(result.truncated).toBe(true);const raw=readFileSync(result.output_ref);expect(raw.subarray(0,8*1024*1024)).toEqual(Buffer.alloc(8*1024*1024,"x"));expect(raw.subarray(8*1024*1024).toString()).toBe("\n[TRUNCATED: output exceeded 8 MiB]\n");});
});
