import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import {selectAffectedCases}from"../../workflows/build-code/case-selection.mjs";import{readCurrentTestAssetRegistry}from"../../workflows/build-code/test-asset-inventory.mjs";

function registryFixture({names=["first","second"],ids,skip=false}={}){const r=root(),repo=join(r,"repo"),wt=join(r,"wt");repository(repo);mkdirSync(join(repo,"tests"));mkdirSync(join(repo,"docs/quality"),{recursive:true});const target="tests/owned.test.mjs",command=`node --test --test-reporter=tap ${target}`,source=['import {test} from "node:test";',...names.map((n,i)=>`test(${JSON.stringify(n)}, ${i===1&&skip?"{skip:true}, ":""}()=>{});`)].join("\n")+"\n";writeFileSync(join(repo,target),source);writeFileSync(join(repo,"docs/quality/test-asset-registry.json"),JSON.stringify({schema:"workflowhub-test-asset-registry.v1",revision:"owned.1",outside_scope:"unknown",targets:[{path:target,runner:"node:test",command,status:"active",owner:"owned",sha256:"old-passive-data",registered_test_ids:ids??[`${target} > first`,`${target} > second`]}]})+"\n");git(repo,"add",".");git(repo,"commit","-qm","owned registry");const baseline=git(repo,"rev-parse","HEAD");git(repo,"worktree","add","-q","-b","task/owned/consumer",wt,"main");const records=join(r,"records");mkdirSync(records);return{r,repo,wt,records,target,command,workspace:{targetRepoRoot:repo,worktreeRoot:wt,branch:"task/owned/consumer",baselineCommit:baseline},source};}

const catalog=(target="tests/owned.test.mjs")=>({revision:"owned.1",cases:[{id:"PRODUCT",status:"active",change_triggers:["product.mjs"],related_case_ids:[],execution:{target,expected_test_identity:"first",machine_command:`node --test --test-reporter=tap ${target}`,registered_test_ids:[`${target} > first`,`${target} > second`]}}]});
const scope=paths=>({status:"recorded",changed_paths:paths});
describe("ordinary observed change to candidate selection",()=>{
 it.each(["alpha","beta"])("selects only changed %s product and linked regression",label=>{const a={id:"A",status:"active",change_triggers:["a.mjs"],related_case_ids:["RA"],execution:{target:"tests/a.test.mjs",expected_test_identity:"A"}},ra={...a,id:"RA",change_triggers:["old-a.mjs"],related_case_ids:["A"],execution:{target:"tests/ra.test.mjs",expected_test_identity:"RA"}},b={...a,id:"B",change_triggers:["b.mjs"],related_case_ids:["RB"],execution:{target:"tests/b.test.mjs",expected_test_identity:"B"}},rb={...b,id:"RB",change_triggers:["old-b.mjs"],related_case_ids:["B"],execution:{target:"tests/rb.test.mjs",expected_test_identity:"RB"}};const cases=[a,ra,b,rb],inventory={tests:cases.map(c=>({test_file:c.execution.target,full_id:c.execution.expected_test_identity,status:"registered"}))};const selected=selectAffectedCases({changeScope:scope([label==="alpha"?"a.mjs":"b.mjs"]),catalog:{revision:"owned.1",cases},inventory});expect(selected.status).toBe("selected");expect(selected.cases.map(x=>x.id).sort()).toEqual(label==="alpha"?["A","RA"]:["B","RB"]);expect(selected.provenance).toBe("supplied_unverified");});
 it("keeps unknown scope and missing inventory unavailable",()=>{expect(selectAffectedCases({changeScope:{status:"unknown",changed_paths:[]}})).toMatchObject({status:"unavailable",reason:"unknown_change_scope",cases:[]});expect(selectAffectedCases({changeScope:scope(["product.mjs"]),catalog:catalog(),inventory:{tests:[]}})).toMatchObject({status:"unavailable",reason:"missing_inventory_identity",cases:[]});});
 it("uses a real finite pre-run registry without claiming execution or snapshot authority",async()=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace}),result=selectAffectedCases({changeScope:scope(["product.mjs"]),catalog:catalog(),registry});expect(result).toMatchObject({status:"selected",test_execution_status:"not_run",registry_revision:"owned.1"});expect(result.cases.map(x=>x.id)).toEqual(["PRODUCT"]);for(const k of["task_id","snapshot_tree","source_digest","registry_sha256","receipt_ref","observations"])expect(result).not.toHaveProperty(k);});
 it.each([undefined,"unknown","pending"])("rejects a case with unrecognized status %s",async status=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace}),c=catalog();c.cases[0].status=status;expect(selectAffectedCases({changeScope:scope(["product.mjs"]),catalog:c,registry})).toMatchObject({status:"unavailable",reason:"missing_inventory_identity",cases:[]});});
 it("rejects unknown related and retired cases",async()=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace});const c=catalog();c.cases[0].related_case_ids=["MISSING"];expect(selectAffectedCases({changeScope:scope(["product.mjs"]),catalog:c,registry}).reason).toBe("missing_inventory_identity");c.cases[0].related_case_ids=[];c.cases[0].status="retired";expect(selectAffectedCases({changeScope:scope(["product.mjs"]),catalog:c,registry})).toMatchObject({status:"unavailable",reason:"unmapped_changed_path",cases:[]});});
 it("keeps known support/history out of business mapping while each unknown remains visible",async()=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace});const known=selectAffectedCases({changeScope:scope(["product.mjs","tests/owned.test.mjs","docs/fixture.md","specs/archive/old/spec.md",".planning/task.md"]),catalog:catalog(),registry});expect(known.status).toBe("selected");expect(known.scope_summary).toEqual({total_changed_paths:5,business_case_paths:1,supporting_paths:3,out_of_scope_paths:1,unknown_paths:0});const mixed=selectAffectedCases({changeScope:scope(["unknown-a.mjs","product.mjs","unknown-b.mjs"]),catalog:catalog(),registry});expect(mixed).toMatchObject({status:"unavailable",reason:"unmapped_changed_path",unmapped_changed_paths:["unknown-a.mjs","unknown-b.mjs"],test_execution_status:"not_run"});expect(mixed.cases.map(x=>x.id)).toEqual(["PRODUCT"]);expect(selectAffectedCases({changeScope:scope(["unknown-only.mjs"]),catalog:catalog(),registry}).cases).toEqual([]);});
 it.each(["wrong-reference","unregistered-leaf","duplicate-leaf","both-inventories"])("rejects %s finite runnable contradiction",async fault=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace}),c=catalog(),args={changeScope:scope(["product.mjs"]),catalog:c,registry};if(fault==="wrong-reference")args.registry={...registry,registry_ref:"docs/other.json"};if(fault==="unregistered-leaf")c.cases[0].execution.registered_test_ids=[`${f.target} > absent`];if(fault==="duplicate-leaf")c.cases[0].execution.registered_test_ids=[`${f.target} > first`,`${f.target} > first`];if(fault==="both-inventories")args.inventory={tests:[]};expect(selectAffectedCases(args)).toMatchObject({status:"unavailable",reason:"missing_inventory_identity",cases:[]});});
});
