import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import {readCurrentTestAssetRegistry,collectRegisteredTestInventory}from"../../workflows/build-code/test-asset-inventory.mjs";import{runCapture}from"../../workflows/build-code/capture.mjs";

function registryFixture({names=["first","second"],ids,skip=false}={}){const r=root(),repo=join(r,"repo"),wt=join(r,"wt");repository(repo);mkdirSync(join(repo,"tests"));mkdirSync(join(repo,"docs/quality"),{recursive:true});const target="tests/owned.test.mjs",command=`node --test --test-reporter=tap ${target}`,source=['import {test} from "node:test";',...names.map((n,i)=>`test(${JSON.stringify(n)}, ${i===1&&skip?"{skip:true}, ":""}()=>{});`)].join("\n")+"\n";writeFileSync(join(repo,target),source);writeFileSync(join(repo,"docs/quality/test-asset-registry.json"),JSON.stringify({schema:"workflowhub-test-asset-registry.v1",revision:"owned.1",outside_scope:"unknown",targets:[{path:target,runner:"node:test",command,status:"active",owner:"owned",sha256:"old-passive-data",registered_test_ids:ids??[`${target} > first`,`${target} > second`]}]})+"\n");git(repo,"add",".");git(repo,"commit","-qm","owned registry");const baseline=git(repo,"rev-parse","HEAD");git(repo,"worktree","add","-q","-b","task/owned/consumer",wt,"main");const records=join(r,"records");mkdirSync(records);return{r,repo,wt,records,target,command,workspace:{targetRepoRoot:repo,worktreeRoot:wt,branch:"task/owned/consumer",baselineCommit:baseline},source};}

async function observed(f,command=f.command){const receipt=await runCapture({cwd:f.wt,recordDir:f.records,slug:"owned-tap",argv:[process.execPath,"--test","--test-reporter=tap",command.split(" ").at(-1)]});return{receipt,value:await collectRegisteredTestInventory({workspace:f.workspace,output:readFileSync(receipt.output_ref,"utf8"),command,exitCode:receipt.exit_code,outputRef:receipt.output_ref})};}
describe("ordinary source-owned registry versus real runnable leaves",()=>{
 it("reads the actual finite source registration and exactly two real passing TAP leaves",async()=>{const f=registryFixture(),registry=await readCurrentTestAssetRegistry({workspace:f.workspace});expect(registry).toMatchObject({status:"recorded",revision:"owned.1",outside_scope:"unknown"});expect(registry.targets[0].sha256).toBe("old-passive-data");const{receipt,value}=await observed(f);expect(value).toMatchObject({status:"recorded",tests:[{full_id:`${f.target} > first`,status:"passed"},{full_id:`${f.target} > second`,status:"passed"}],missing:[],unmatched:[],skipped:[]});expect(value.output_ref).toBe(receipt.output_ref);expect(JSON.parse(readFileSync(receipt.receipt_ref))).not.toHaveProperty("test_inventory");});
 it.each(["missing","extra","skipped"])("reports actual %s leaves without claiming coverage",async kind=>{const f=registryFixture(kind==="missing"?{names:["first"]}:kind==="extra"?{ids:["tests/owned.test.mjs > first"]}:{skip:true});const{value}=await observed(f);expect(value.status).toBe("inconsistent");expect(value.reason).toBe(kind==="skipped"?"skipped_test_leaf":"registry_reporter_leaf_mismatch");expect(value[kind==="missing"?"missing":kind==="extra"?"unmatched":"skipped"]).toContain(`${f.target} > second`);});
 it("rejects duplicate registered identities before any child execution",async()=>{const f=registryFixture({ids:["tests/owned.test.mjs > first","tests/owned.test.mjs > first"]});await expect(readCurrentTestAssetRegistry({workspace:f.workspace})).rejects.toThrow(/duplicate.*registered/);expect(readdirSync(f.records)).toEqual([]);});
 it("rejects an observed command outside the active finite target",async()=>{const f=registryFixture();await expect(collectRegisteredTestInventory({workspace:f.workspace,output:"TAP version 13\n",command:"node --test --test-reporter=tap tests/other.test.mjs",exitCode:0})).rejects.toThrow(/not in.*active.*registry/);});
 it("rereads current source while old hashes remain passive and actual new leaf loss is diagnosed",async()=>{const f=registryFixture();writeFileSync(join(f.wt,f.target),'import {test}from"node:test";test("first",()=>{});\n');expect((await readCurrentTestAssetRegistry({workspace:f.workspace})).targets[0].sha256).toBe("old-passive-data");const{value}=await observed(f);expect(value).toMatchObject({status:"inconsistent",reason:"registry_reporter_leaf_mismatch",missing:[`${f.target} > second`]});});
 it.each(["symlink","hardlink"])("rejects %s registry source alias",async kind=>{const f=registryFixture(),p=join(f.wt,f.target);rmSync(p);if(kind==="symlink")symlinkSync(join(f.repo,f.target),p);else linkSync(join(f.repo,f.target),p);await expect(readCurrentTestAssetRegistry({workspace:f.workspace})).rejects.toThrow(/alias|single.link|unsafe|regular/);});
});
