import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";
const ref=new URL("../../docs/quality/business-case-catalog.json",import.meta.url);
const nonempty=x=>typeof x==="string"&&x.trim().length>0;
// Existing historical catalogue bytes remain readable. Old paths/registration/hash
// are descriptive history, never current source certification or tested coverage.
describe("ordinary sourced business catalogue relationships",()=>{
 it("retains unique explicit case rules, related edges and real scenario meaning",()=>{const before=readFileSync(ref),c=JSON.parse(before);expect(c.schema).toBe("workflowhub-business-case-catalog.v1");expect(c.project).toBe("workflowhub");expect(nonempty(c.owner)).toBe(true);expect(c.uncharted_legacy).toMatchObject({status:"unknown"});const cases=new Map(c.cases.map(e=>[e.id,e]));expect(cases.size).toBe(c.cases.length);for(const e of c.cases){expect(nonempty(e.id)&&nonempty(e.owner)&&nonempty(e.source.path)&&nonempty(e.rule.statement)).toBe(true);expect(["feature","regression"]).toContain(e.intent);for(const name of["normal","failure","boundary","recovery"]){for(const field of["precondition","input","observable_success","observable_failure"])expect(nonempty(e.scenarios[name][field]),`${e.id}/${name}/${field}`).toBe(true);}for(const key of["change_triggers","implementation_interfaces","consumers","ac_ids","task_ids","phase_ids"])expect(Array.isArray(e[key])&&e[key].length>0).toBe(true);for(const related of e.related_case_ids)expect(cases.has(related),`${e.id} undeclared relationship`).toBe(true);expect(nonempty(e.execution.target)&&nonempty(e.execution.expected_test_identity)).toBe(true);}expect(readFileSync(ref)).toEqual(before);});
 it("keeps P9–P12 unknown obligations explicit rather than inventing business coverage",()=>{const c=JSON.parse(readFileSync(ref)),rows=c.evolution.phase_obligations;expect(rows.length).toBeGreaterThan(0);expect(new Set(rows.map(r=>`${r.phase_id}/${r.task_id}/${r.test_target}`)).size).toBe(rows.length);for(const phase of["P9","P10","P11","P12"])expect(rows.some(r=>r.phase_id===phase)).toBe(true);for(const r of rows){expect(nonempty(r.owner)&&nonempty(r.impact)&&nonempty(r.source_path)&&nonempty(r.consumer_path)).toBe(true);expect(r.promotion_trigger).toMatch(/source.*consumer.*runner.*oracle/i);if(r.status==="not_done"){expect(r.case_id).toBeNull();expect(r.business_rule_status).toBe("unknown");}}expect(rows.some(r=>r.status==="not_done")).toBe(true);expect(c.evolution.unmapped_b2_status).toBe("unknown");expect(c.uncharted_legacy.status).not.toBe("covered");});
});
