import { afterEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function git(cwd,args){const env={...process.env};for(const key of Object.keys(env))if(key.startsWith("GIT_"))delete env[key];return execFileSync("git",args,{cwd,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();}
function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"workflowhub-current-human-auth-")));roots.push(root);const repo=join(root,"repo");mkdirSync(repo);git(repo,["init","-q","-b","main"]);git(repo,["config","user.name","Owned primitive test"]);git(repo,["config","user.email","owned@test.invalid"]);writeFileSync(join(repo,"README.md"),"owned baseline\n");git(repo,["add","README.md"]);git(repo,["commit","-qm","owned baseline"]);return{root,repo,head:git(repo,["rev-parse","HEAD"]),dir:join(root,"quality","evidence","git-authorizations")};}
const authorizeUrl=new URL("../../runtime/interface/git-authorize.mjs",import.meta.url).href;
function authorization(state,action,fields,dir=state.dir){
 const code=`import {recordAuthorization,consumeAuthorization} from ${JSON.stringify(authorizeUrl)};const action=${JSON.stringify(action)},fields=${JSON.stringify({...fields,dir})};try{const value=await (action==='record'?recordAuthorization(fields):consumeAuthorization(fields));process.stdout.write(JSON.stringify({ok:true,value}));}catch(error){process.stdout.write(JSON.stringify({ok:false,code:error.code??null,message:error.message}));}`;
 const env={...process.env};for(const key of Object.keys(env))if(key.startsWith("GIT_"))delete env[key];
 return JSON.parse(execFileSync(process.execPath,["--input-type=module","-e",code],{cwd:state.repo,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}));
}
const jsonFiles=dir=>existsSync(dir)?readdirSync(dir).filter(x=>x.endsWith(".json")):[];
describe("current tool④ authorization failure diagnostics, without receipt certification",()=>{
 it("requires an actual unused ordinary grant before consumption",()=>{const f=fixture(),r=authorization(f,"consume",{operation:"commit",stepId:"owned-step"});expect(r).toMatchObject({ok:false,code:"IRREVERSIBLE_AUTHORIZATION_REQUIRED"});expect(r.message).toContain("no unused authorization for commit");expect(jsonFiles(f.dir)).toEqual([]);});
 it("rejects unsupported operation before creating authorization storage",()=>{const f=fixture(),r=authorization(f,"record",{operation:"rebind",confirmationRef:"owned-confirmation.json"});expect(r).toMatchObject({ok:false,code:"UNSUPPORTED_OPERATION"});expect(existsSync(f.dir)).toBe(false);});
 it("reports stale actual Git HEAD without consuming or rewriting the original grant",()=>{const f=fixture(),grant=authorization(f,"record",{operation:"commit",confirmationRef:"owned-confirmation.json"});expect(grant.ok).toBe(true);const raw=readFileSync(grant.value);writeFileSync(join(f.repo,"README.md"),"owned next head\n");git(f.repo,["add","README.md"]);git(f.repo,["commit","-qm","owned next"]);const r=authorization(f,"consume",{operation:"commit",stepId:"next-step"});expect(r).toMatchObject({ok:false,code:"AUTHORIZATION_HEAD_MISMATCH"});expect(r.message).toContain("HEAD changed since authorization");expect(readFileSync(grant.value)).toEqual(raw);expect(jsonFiles(f.dir)).toHaveLength(1);});
 it("reports a missing confirmation reference before creating any records",()=>{const f=fixture(),r=authorization(f,"record",{operation:"commit",confirmationRef:""});expect(r).toMatchObject({ok:false,code:"CONFIRMATION_REFERENCE_REQUIRED"});expect(existsSync(f.dir)).toBe(false);});
 it("keeps the real branch, HEAD and explicit plain confirmation reference as provenance",()=>{const f=fixture(),ref="quality/evidence/human-confirmations/owned.json",r=authorization(f,"record",{operation:"commit",confirmationRef:ref});expect(r.ok).toBe(true);const raw=readFileSync(r.value),record=JSON.parse(raw);expect(record).toMatchObject({operation:"commit",branch:"main",head:f.head,confirmation_ref:ref});expect(record).not.toHaveProperty("subject_hash");expect(record).not.toHaveProperty("resolved_review");expect(record).not.toHaveProperty("snapshot_tree");expect(readFileSync(r.value)).toEqual(raw);});
 it("surfaces bad stored JSON rather than hiding it as a missing grant",()=>{const f=fixture(),grant=authorization(f,"record",{operation:"commit",confirmationRef:"owned.json"});expect(grant.ok).toBe(true);const corrupt=Buffer.from("{bad json\n");writeFileSync(grant.value,corrupt);const r=authorization(f,"consume",{operation:"commit",stepId:"owned-step"});expect(r).toMatchObject({ok:false,code:"AUTHORIZATION_RECORD_INVALID"});expect(r.message).toContain("invalid authorization JSON");expect(readFileSync(grant.value)).toEqual(corrupt);expect(jsonFiles(f.dir)).toHaveLength(1);});
 it("consumes once, retries the same actual step, and rejects another step without changing original records",()=>{const f=fixture(),grant=authorization(f,"record",{operation:"commit",confirmationRef:"owned.json"});expect(grant.ok).toBe(true);const original=readFileSync(grant.value);const first=authorization(f,"consume",{operation:"commit",stepId:"owned-step"});expect(first.ok).toBe(true);const raw=readFileSync(first.value.path);expect(first.value).toMatchObject({operation:"commit",step_id:"owned-step",authorization_ref:grant.value});const retry=authorization(f,"consume",{operation:"commit",stepId:"owned-step"});expect(retry).toEqual(first);const other=authorization(f,"consume",{operation:"commit",stepId:"other-step"});expect(other).toMatchObject({ok:false,code:"AUTHORIZATION_ALREADY_CONSUMED"});expect(readFileSync(grant.value)).toEqual(original);expect(readFileSync(first.value.path)).toEqual(raw);expect(jsonFiles(f.dir)).toHaveLength(2);});
});
