import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import{bootstrapTask}from"../../tools/cli/task-bootstrap.mjs";
const cli=new URL("../../tools/cli/stage-runtime.mjs",import.meta.url).href;
async function fixture(){const r=root(),repo=join(r,"repo"),storage=join(r,"storage"),home=join(r,"home");repository(repo);mkdirSync(storage);mkdirSync(home);const boot=await bootstrapTask({project:"OwnedEntry",task:"current-entry", "target-repo":repo},{env:{HOME:home,WORKFLOWHUB_TASK_DIR:storage},home,cwd:repo});const wt=boot.workspace.worktree_root,material=join(wt,"specs/current-entry");mkdirSync(join(material,"phases"),{recursive:true});for(const[name,text]of Object.entries({"decision-log.md":"# Current decision\n\n## 任务身份\n- **任务类型**：普通任务\n", "spec.md":"# Current specification\n", "phases/index.md":"## Execution Index\n\n| phase | authority ref | semantic anchor | write set | dependency | consumer |\n| --- | --- | --- | --- | --- | --- |\n| `P1` | `phases/P1.md` | owned | README.md | none | build-code |\n", "phases/P1.md":"# Phase P1\n\n### T001 — Owned current task\n"}))writeFileSync(join(material,name),text);git(wt,"add","specs");git(wt,"commit","-qm","owned current materials");return{r,repo,storage,home,wt,material,taskPath:boot.task_path,n:0};}
function call(f,behavior,action,{stage="build-code",input,extra=[],review=false}={}){const argv=[behavior,`--action=${action}`,`--stage=${stage}`,"--project=OwnedEntry","--task=current-entry",`--task-path=${f.taskPath}`,...extra];if(input!==undefined){const p=join(f.wt,`input-${++f.n}.json`);writeFileSync(p,JSON.stringify(input)+"\n");argv.push(`--input=${p}`);}const code=`import{stageRuntimeCliMain}from${JSON.stringify(cli)};try{const value=await stageRuntimeCliMain(JSON.parse(process.argv[1]),${review?'{services:{runReviewRound:async(request,options)=>{await options.onProviderOutput({provider:"owned/stub",output:Buffer.from([0xff,0x00,0x41])});return{status:"unavailable",dispatch_state:"unknown",findings:[],provider_results:[],error:{code:"OWNED_UNAVAILABLE",message:"controlled no-model review"}};}}}':'{}'});console.log(JSON.stringify({ok:true,value}));}catch(error){console.log(JSON.stringify({ok:false,error:{code:error.code??null,message:error.message}}));}`;const result=spawnSync(process.execPath,["--input-type=module","-e",code,JSON.stringify(argv)],{cwd:f.wt,env:{...env(),HOME:f.home,XDG_CONFIG_HOME:join(f.home,".config"),WORKFLOWHUB_TASK_DIR:f.storage},encoding:"utf8",timeout:15000,stdio:["ignore","pipe","pipe"]});expect(result.error).toBeUndefined();expect(result.status).toBe(0);return JSON.parse(result.stdout);}
function originalFacts(f){return readFileSync(join(f.taskPath,"facts.jsonl"));}

describe("human confirmation remains distinct from Git authorization and quality",()=>{
 it("records exact reply/material references without advancing facts or authorizing an irreversible operation",async()=>{const f=await fixture(),before=originalFacts(f),head=git(f.wt,"rev-parse","HEAD");const result=call(f,"confirm","decision",{stage:"build-plan",extra:["--decision=accepted-risk","--reply-text=I accept this specific controlled risk.","--material-ref=spec.md"]});expect(result.ok).toBe(true);expect(JSON.parse(readFileSync(result.value.path))).toMatchObject({decision:"accepted-risk",reply:"I accept this specific controlled risk.",material_refs:["spec.md"],head});expect(originalFacts(f)).toEqual(before);expect(existsSync(join(f.taskPath,"quality/evidence/git-authorizations"))).toBe(false);expect(call(f,"status","begin").value.quality_status).toBe("unknown");});
 it("requires an explicit separate operation and nonempty confirmation reference",async()=>{const f=await fixture(),before=originalFacts(f),invalid=call(f,"authorize","commit",{extra:["--subject-ref="]});expect(invalid.ok).toBe(false);expect(invalid.error.message).toMatch(/subject.ref/);expect(originalFacts(f)).toEqual(before);const confirm=call(f,"confirm","decision",{extra:["--decision=approved","--reply-text=Approve the owned proposed change.","--material-ref=spec.md"]});const grant=call(f,"authorize","archive",{extra:[`--subject-ref=${confirm.value.path}`]});expect(grant.ok).toBe(true);expect(JSON.parse(readFileSync(grant.value.path))).toMatchObject({operation:"archive",confirmation_ref:confirm.value.path,head:git(f.wt,"rev-parse","HEAD")});expect(originalFacts(f)).toEqual(before);});
 it("rejects empty human replies and removed close/legacy confirmation inputs without manufacturing facts",async()=>{const f=await fixture(),before=originalFacts(f);expect(call(f,"confirm","decision",{extra:["--decision=approved","--reply-text="]})).toMatchObject({ok:false,error:{code:"CONFIRMATION_REPLY_REQUIRED"}});const legacy=call(f,"confirm","decision",{extra:["--decision=approved","--reply-text=owned","--attempt=old-machine-subject"]});expect(legacy.ok).toBe(false);expect(legacy.error.message).toBe("confirm has unknown options: attempt");expect(call(f,"authorize","close",{extra:["--subject-ref=owned.json"]})).toMatchObject({ok:false,error:{message:"unknown public runtime action"}});expect(originalFacts(f)).toEqual(before);});
});
