import { afterEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function git(cwd,args){const env={...process.env};for(const key of Object.keys(env))if(key.startsWith("GIT_"))delete env[key];return execFileSync("git",args,{cwd,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();}
function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"workflowhub-current-human-auth-")));roots.push(root);const repo=join(root,"repo");mkdirSync(repo);git(repo,["init","-q","-b","main"]);git(repo,["config","user.name","Owned primitive test"]);git(repo,["config","user.email","owned@test.invalid"]);writeFileSync(join(repo,"README.md"),"owned baseline\n");git(repo,["add","README.md"]);git(repo,["commit","-qm","owned baseline"]);return{root,repo,head:git(repo,["rev-parse","HEAD"]),dir:join(root,"quality","evidence","git-authorizations")};}
const authorizeUrl=new URL("../../runtime/interface/git-authorize.mjs",import.meta.url).href;
function authorization(state,action,fields,dir=state.dir){
 const code=`import {recordAuthorization,consumeAuthorization} from ${JSON.stringify(authorizeUrl)};const action=${JSON.stringify(action)},fields=${JSON.stringify({...fields,dir})};try{const value=await (action==='record'?recordAuthorization(fields):consumeAuthorization(fields));process.stdout.write(JSON.stringify({ok:true,value}));}catch(error){process.stdout.write(JSON.stringify({ok:false,code:error.code??null,message:error.message}));}`;
 const env={...process.env};for(const key of Object.keys(env))if(key.startsWith("GIT_"))delete env[key];
 return JSON.parse(execFileSync(process.execPath,["--input-type=module","-e",code],{cwd:state.repo,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}));
}
const jsonFiles=dir=>existsSync(dir)?readdirSync(dir).filter(x=>x.endsWith(".json")):[];
import { recordConfirmation } from "../../runtime/interface/human-confirm.mjs";
const humanDir=f=>join(f.root,"quality","evidence","human-confirmations");
const fields={stage:"build-code",decision:"accepted",reply:"  我确认当前普通材料。\r\n保留原话。  ",materialRefs:["specs/owned/spec.md","specs/owned/phases/P1.md"]};
describe("current tool⑦ explicit human reply records",()=>{
 it("records the verbatim reply, plain material references and actual Git HEAD in one immutable ordinary original",async()=>{const f=fixture(),path=(await recordConfirmation(fields,{cwd:f.repo,dir:humanDir(f)})).path,raw=readFileSync(path),r=JSON.parse(raw);expect(r).toMatchObject({stage:fields.stage,decision:fields.decision,reply:fields.reply,material_refs:fields.materialRefs,head:f.head});expect(Object.keys(r).sort()).toEqual(["stage","decision","reply","material_refs","head","created_at"].sort());expect(r).not.toHaveProperty("coverage_quality_fact_ref");expect(readFileSync(path)).toEqual(raw);});
 it("uses the stored confirmation reference in tool④ without manufacturing a review, hash or coverage permit",async()=>{const f=fixture(),path=(await recordConfirmation(fields,{cwd:f.repo,dir:humanDir(f)})).path,raw=readFileSync(path);const grant=authorization(f,"record",{operation:"commit",confirmationRef:path});expect(grant.ok).toBe(true);expect(JSON.parse(readFileSync(grant.value))).toMatchObject({operation:"commit",head:f.head,confirmation_ref:path});expect(readFileSync(path)).toEqual(raw);expect(existsSync(join(f.root,"quality","verify.v1"))).toBe(false);});
 it("appends a distinct record and preserves the first original rather than reconstructing deterministic request identity",async()=>{const f=fixture(),first=(await recordConfirmation(fields,{cwd:f.repo,dir:humanDir(f)})).path,raw=readFileSync(first);const secondFields={...fields,reply:"第二次明确确认。"},second=(await recordConfirmation(secondFields,{cwd:f.repo,dir:humanDir(f)})).path;expect(second).not.toBe(first);expect(jsonFiles(humanDir(f))).toHaveLength(2);expect(readFileSync(first)).toEqual(raw);expect(JSON.parse(readFileSync(second)).reply).toBe(secondFields.reply);});
 it("rejects missing reply before any directory or record effects",async()=>{const f=fixture();await expect(recordConfirmation({...fields,reply:""},{cwd:f.repo,dir:humanDir(f)})).rejects.toMatchObject({code:"CONFIRMATION_REPLY_REQUIRED"});expect(existsSync(humanDir(f))).toBe(false);});
 it("rejects caller supplied HEAD or retired hash and step fields before storage instead of trusting them",async()=>{for(const extra of[{head:"0".repeat(40)},{subject_hash:"f".repeat(64)},{step_slug:"old-step"}]){const f=fixture();await expect(recordConfirmation({...fields,...extra},{cwd:f.repo,dir:humanDir(f)})).rejects.toMatchObject({code:"INVALID_CONFIRMATION"});expect(existsSync(humanDir(f))).toBe(false);}});
 it("rejects invalid material reference shape before writing",async()=>{for(const materialRefs of[null,[""],["bad\0ref"]]){const f=fixture();await expect(recordConfirmation({...fields,materialRefs},{cwd:f.repo,dir:humanDir(f)})).rejects.toMatchObject({code:"INVALID_MATERIAL_REFS"});expect(existsSync(humanDir(f))).toBe(false);}});
 it("binds each invocation to its actual current Git HEAD without rewriting a prior reply",async()=>{const f=fixture(),first=(await recordConfirmation(fields,{cwd:f.repo,dir:humanDir(f)})).path,raw=readFileSync(first);writeFileSync(join(f.repo,"README.md"),"owned new decision head\n");git(f.repo,["add","README.md"]);git(f.repo,["commit","-qm","owned new"]);const second=(await recordConfirmation(fields,{cwd:f.repo,dir:humanDir(f)})).path;expect(JSON.parse(readFileSync(second)).head).toBe(git(f.repo,["rev-parse","HEAD"]));expect(JSON.parse(readFileSync(second)).head).not.toBe(f.head);expect(readFileSync(first)).toEqual(raw);});
 it("fails a real non-Git context before creating human record storage",async()=>{const f=fixture(),nonGit=join(f.root,"non-git");mkdirSync(nonGit);await expect(recordConfirmation(fields,{cwd:nonGit,dir:humanDir(f)} )).rejects.toMatchObject({code:"GIT_COMMAND_FAILED"});expect(existsSync(humanDir(f))).toBe(false);});
});
