import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import{openTask}from"../../runtime/task/task-handle.mjs";import{readCurrentEvolutionProjection}from"../../runtime/evidence/workflow-evolution.mjs";
function historyFixture(){const r=root(),taskPath=join(r,"Projects/Demo/tasks/history-lessons"),quality=join(taskPath,"quality/evidence");mkdirSync(quality,{recursive:true});const manifest={schema_version:"1.0.0",project_name:"Demo",task_id:"history-lessons",target_repo_root:r,activation_cohort:"history"};writeFileSync(join(taskPath,"task.json"),JSON.stringify(manifest)+"\n");const rows=[{entry_kind:"raw_observation",id:"raw-1",text:"原始观察",reflection_ref:"quality/stage-reflection/build-code.json"},{entry_kind:"merged_lesson",id:"lesson-1",text:"历史合并结论",source_entry_ids:["raw-1"],source_refs:["quality/stage-reflection/build-code.json"]}],bytes=Buffer.from(rows.map(JSON.stringify).join("\n")+"\n"),ref="quality/evidence/lessons.jsonl";writeFileSync(join(taskPath,ref),bytes);return{r,taskPath,ref,bytes,task:openTask(taskPath,"Demo","history-lessons")};}
describe("read-only historical lesson observations and provenance",()=>{
 it("reads prior raw and merged observations without dropping rows or rewriting bytes",()=>{const f=historyFixture(),raw=f.task.readRecordBytes(f.ref);expect(raw).toEqual(f.bytes);const rows=raw.toString().trimEnd().split("\n").map(JSON.parse);expect(rows.map(r=>r.entry_kind)).toEqual(["raw_observation","merged_lesson"]);expect(rows[1].source_entry_ids).toEqual([rows[0].id]);expect(rows[1].source_refs).toEqual([rows[0].reflection_ref]);expect(readFileSync(join(f.taskPath,f.ref))).toEqual(f.bytes);});
 it("keeps malformed old JSON explicit and forbids new writes before effects",async()=>{const f=historyFixture(),bad=Buffer.from('{bad json}\n');writeFileSync(join(f.taskPath,f.ref),bad);expect(()=>JSON.parse(f.task.readRecord(f.ref))).toThrow(SyntaxError);await expect(f.task.createRecord("quality/evidence/new-lesson.json","{}\n")).rejects.toThrow(/read.only/);expect(readFileSync(join(f.taskPath,f.ref))).toEqual(bad);expect(existsSync(join(f.taskPath,"quality/evidence/new-lesson.json"))).toBe(false);});
 it.each(["symlink","hardlink"])("rejects %s historical lesson aliases without reading a foreign source",kind=>{const f=historyFixture(),source=join(f.r,"foreign.jsonl");writeFileSync(source,"foreign owned control\n");rmSync(join(f.taskPath,f.ref));if(kind==="symlink")symlinkSync(source,join(f.taskPath,f.ref));else linkSync(source,join(f.taskPath,f.ref));expect(()=>f.task.readRecord(f.ref)).toThrow(/alias|single.link/);expect(readFileSync(source,"utf8")).toBe("foreign owned control\n");});
 it("reads a committed historical candidate's source references without a lesson refresh or mkdir",()=>{const r=root(),project=join(r,"Projects/Demo");mkdirSync(project,{recursive:true});const source=join(project,"evolution-candidates.jsonl"),batch={schema_version:"workflow-evolution.v1",project:"Demo",batch_id:"old-batch"},candidate={...batch,record_kind:"candidate",candidate_id:"old-lesson",candidate_group_id:"history",tier:"reference_only",lifecycle_status:"deferred",row_status:"historical",freshness:"stale",evidence_status:"unknown",sample_status:"insufficient_samples",validation_status:"unverified",source_refs:["quality/stage-reflection/build-code.json"]},bytes=Buffer.from([JSON.stringify({...batch,record_kind:"batch_begin"}),JSON.stringify(candidate),JSON.stringify({...batch,record_kind:"batch_commit",status:"committed",count:1})].join("\n")+"\n");writeFileSync(source,bytes);const result=readCurrentEvolutionProjection({storageRoot:r,project:"Demo"});expect(result).toMatchObject({status:"ok",historical:true,candidates:[{candidate_id:"old-lesson",source_refs:candidate.source_refs}]});expect(readFileSync(source)).toEqual(bytes);const missing=join(r,"missing-project");expect(readCurrentEvolutionProjection({storageRoot:missing,project:"Demo"}).status).toBe("unavailable");expect(existsSync(missing)).toBe(false);});
});
