import {afterEach,describe,expect,it} from "vitest";import {mkdtempSync,realpathSync,readFileSync,writeFileSync,existsSync,rmSync} from "node:fs";import{tmpdir}from"node:os";import{join}from"node:path";
import{createTask,openTask}from"../../runtime/task/task-handle.mjs";import{initializeTaskStore}from"../../runtime/task/task-store.mjs";import{loadPortableWorkflowManifest,runPortableWorkflow,readLatestPortableTerminal,projectPortableWorkflowStatus}from"../../runtime/task/portable-workflow-run.mjs";
const ROOT=new URL("../..",import.meta.url).pathname,roots=[];afterEach(()=>{for(const r of roots.splice(0))rmSync(r,{recursive:true,force:true});});
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),"ordinary-portable-outcome-")));roots.push(root);const task=await createTask({storageRoot:root,manifest:{schema_version:"1.0.0",project_name:"workflowhub",task_id:"portable-contract",created_at:"2026-10-03T00:00:00Z",target_repo_root:root,activation_cohort:"post",record_model:"vnext-single-write",execution_mode:"per_invocation",issue_ids:[],inputs:{}}});await initializeTaskStore(task.taskPath,{taskId:task.identity.taskId});return{root,task};}
async function input(task,manifest,status="completed"){const rows=manifest.steps.map(s=>({task_id:task.identity.taskId,workflow:"build-prd",step_id:s.step_id,step_slug:s.step_slug,status,...(status==="blocked"?{dependency:"owned service",unblock_condition:"service available"}:{})})),ref="quality/evidence/portable-workflow-outcomes/build-prd/2026-10-03-001-owned-steps.json";await task.createRecord(ref,JSON.stringify({task_id:task.identity.taskId,workflow:"build-prd",step_results:rows})+"\n");return{task_id:task.identity.taskId,workflow:"build-prd",step_results:rows.map(r=>({...r,result_ref:ref}))};}
describe("ordinary portable build-prd observations",()=>{
 it("loads the actual declaration without hard-locking a six-step stage topology",()=>{const m=loadPortableWorkflowManifest({worktreeRoot:ROOT});expect(m.stage_slug).toBe("build-prd");expect(m.steps.length).toBeGreaterThan(0);expect(m.steps.map(s=>s.step_id)).toEqual(m.steps.map((_,i)=>i+1));const ordinary={schema_version:"2.0.0",stage_slug:"build-prd",steps:[{step_id:1,step_slug:"owned-one",observable_result:"owned output"}]};expect(loadPortableWorkflowManifest({worktreeRoot:ROOT,read:()=>JSON.stringify(ordinary)}).steps).toHaveLength(1);});
 it("records actual completed outcomes without starting any code-stage row",async()=>{const f=await fixture(),m=loadPortableWorkflowManifest({worktreeRoot:ROOT}),before=readFileSync(join(f.task.taskPath,"facts.jsonl")),r=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:await input(f.task,m)});expect(r.state).toBe("succeeded");expect(readLatestPortableTerminal({task:f.task})).toMatchObject({workflow:"build-prd",state:"succeeded"});expect(readFileSync(join(f.task.taskPath,"facts.jsonl"))).toEqual(before);expect(r).not.toHaveProperty("stage_completed");});
 it("keeps missing results and missing actual evidence as failed observable outcomes",async()=>{const f=await fixture(),m=loadPortableWorkflowManifest({worktreeRoot:ROOT}),valid=await input(f.task,m),missing=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:{...valid,step_results:[]}});expect(missing.state).toBe("failed");expect(missing.terminal.failed_step).toBe(m.steps[0].step_slug);const invalid=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:{...valid,step_results:valid.step_results.map(r=>({...r,result_ref:"quality/evidence/portable-workflow-outcomes/build-prd/missing.json"}))}});expect(invalid.state).toBe("failed");expect(invalid.terminal.reason).toMatch(/evidence is unavailable/);});
 it.each([["completed","succeeded"],["failed","failed"],["in-progress","in-progress"],["unverified","unverified"],["blocked","blocked"],["abandoned","abandoned"],["unavailable","failed"]])("projects actual %s outcome as %s without machine permits",async(status,expected)=>{const f=await fixture(),m=loadPortableWorkflowManifest({worktreeRoot:ROOT}),r=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:await input(f.task,m,status)});expect(r.state).toBe(expected);expect(projectPortableWorkflowStatus({task:f.task}).state).toBe(expected);});
 it("appends immutable outcomes on repeated invocation instead of a resume/checkpoint actor",async()=>{const f=await fixture(),m=loadPortableWorkflowManifest({worktreeRoot:ROOT}),payload=await input(f.task,m),a=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:payload}),raw=f.task.readRecord(a.ref),b=await runPortableWorkflow({task:f.task,worktreeRoot:ROOT,input:payload});expect(b.ref).not.toBe(a.ref);expect(f.task.readRecord(a.ref)).toEqual(raw);expect(readLatestPortableTerminal({task:f.task}).ref).toBe(b.ref);});
 it("keeps historical reads passive and rejects each nonpost write before new directories or records",async()=>{for(const cohort of["pre","history",null,"unknown"]){const f=await fixture(),path=join(f.task.taskPath,"task.json"),v=JSON.parse(readFileSync(path,"utf8"));if(cohort===null)delete v.activation_cohort;else v.activation_cohort=cohort;const raw=JSON.stringify(v)+"\n";writeFileSync(path,raw);const task=openTask(f.task.taskPath,f.task.identity);expect(projectPortableWorkflowStatus({task}).state).toBe("not-started");const dir=join(task.taskPath,"quality/evidence/portable-workflow-outcomes");expect(existsSync(dir)).toBe(false);await expect(runPortableWorkflow({task,worktreeRoot:ROOT,input:{task_id:task.identity.taskId,workflow:"build-prd",step_results:[]}})).rejects.toMatchObject({code:"PORTABLE_TASK_READ_ONLY"});expect(existsSync(dir)).toBe(false);expect(readFileSync(path,"utf8")).toBe(raw);}});
});
