import{readFileSync,existsSync}from"node:fs";import{describe,expect,it}from"vitest";
function original(name){const candidates=[new URL(`../../docs/architecture/${name}`,import.meta.url),new URL(`../../docs/archive/${name}`,import.meta.url)].filter(p=>existsSync(p));expect(candidates,`one original ${name}, no mirror`).toHaveLength(1);return candidates[0];}
// Historical inventory/report hashes are passive values. No old inventory,
// complexity, hard-zero or delivery certification API becomes a runtime gate.
describe("ordinary inventory and original archived reports",()=>{
 it("keeps the one original inventory readable with unique ordinary path/disposition records",()=>{const p=original("repository-inventory.tsv"),raw=readFileSync(p),lines=raw.toString().trimEnd().split("\n");expect(lines[0]).toBe("path\tdisposition\treason\tsha256");const rows=lines.slice(1).map(s=>s.split("\t"));expect(rows.length).toBeGreaterThan(0);expect(new Set(rows.map(r=>r[0])).size).toBe(rows.length);for(const r of rows){expect(r).toHaveLength(4);expect(r[0].length>0&&r[1].length>0&&r[2].length>0).toBe(true);}expect(readFileSync(p)).toEqual(raw);});
 it("keeps the original complexity measurements as historical data rather than current acceptance",()=>{const p=original("complexity-baseline.json"),raw=readFileSync(p),report=JSON.parse(raw);expect(report.schema_version).toBe("workflowhub-complexity-report.v1");expect(report.source).toBeTypeOf("object");expect(report.measurements).toBeTypeOf("object");expect(readFileSync(p)).toEqual(raw);});
 it("reads current declared production and test-only metadata independently of old tree hashes",()=>{const p=new URL("../../docs/architecture/move-map.json",import.meta.url),raw=readFileSync(p),m=JSON.parse(raw);expect(m.entries.some(e=>e.role==="production"&&e.destination==="runtime/interface/run-command.mjs")).toBe(true);expect(m.entries.some(e=>e.role==="test_only")).toBe(true);for(const e of m.entries.filter(e=>e.role==="production"))expect(typeof e.responsibility==="string"&&typeof e.consumer==="string").toBe(true);expect(readFileSync(p)).toEqual(raw);});
});
