import {afterEach,describe,expect,it} from "vitest";
import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import {existsSync,linkSync,mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,symlinkSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";import {join} from "node:path";
import {recordSimpleReviewRequest} from "../../runtime/review/review-record-route.mjs";
import {runReviewRecovery} from "../../skills/wh-review/scripts/wh-review-cli.mjs";
import {stageRuntimeCliMain} from "../../tools/cli/stage-runtime.mjs";
import {validateSchema} from "../../runtime/review/schema-validator.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"wh-review-public-")));roots.push(p);return p;}
function task(){const dir=root();writeFileSync(join(dir,"task.json"),JSON.stringify({task_id:"fixture"}));return dir;}
const request=()=>({stage:"build-code",review_scope:"phase",subject_kind:"phase",phase_id:"P5",materials:{approved_spec:"Current material",test_evidence:{status:"unknown"}}});
const provider=(extra={})=>({provider:"fixture/model",status:"completed",session_id:null,runtime_id:"fixture-runtime",output_ref:null,error:null,identity:{provider:"fixture/model",adapter:"fixture",source_id:"fixture-source",config_id:"fixture-config",model:"fixture-model"},...extra});
const result=(req,extra={})=>({status:"available",stage:req.stage,review_scope:req.review_scope,subject_kind:req.subject_kind,phase_id:req.phase_id,review_track:null,review_kind:null,provider_results:[provider()],findings:[],...extra});
describe("real public review fact route",()=>{
 it("rejects the retired integration scope before creating review storage or dispatching",async()=>{const dir=task();let calls=0;await expect(recordSimpleReviewRequest({taskDir:dir,request:{...request(),review_scope:"integration",subject_kind:"integration"},runRound:async req=>{calls++;return result(req);}})).rejects.toThrow(/phase review_scope; integration review is retired/);expect(calls).toBe(0);expect(existsSync(join(dir,"quality"))).toBe(false);});
 it("writes one actual date-number result plus one raw original with the complete phase tuple",async()=>{const dir=task();let calls=0;const record=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>{calls++;return result(req,{provider_results:[provider({output:JSON.stringify({findings:[]})})]});}});expect(calls).toBe(1);expect(record.result_ref).toMatch(/^quality\/reviews\/\d{4}-\d{2}-\d{2}-\d{3}-build-code-phase-p5\.json$/);const saved=JSON.parse(readFileSync(record.path,"utf8"));expect(saved).toMatchObject({stage:"build-code",review_scope:"phase",subject_kind:"phase",phase_id:"P5",authoritative:false});expect(saved).not.toHaveProperty("snapshot_tree");expect(saved).not.toHaveProperty("material_id");expect(saved.provider_results[0].output_ref).toEqual(expect.any(String));expect(readFileSync(saved.provider_results[0].output_ref,"utf8")).toBe(JSON.stringify({findings:[]}));expect(saved.provider_results[0]).not.toHaveProperty("output");expect(()=>validateSchema("result",saved)).not.toThrow();});
 it("preserves actual broker retry, tuning and failure cost facts without inventing totals",async()=>{const dir=task();const execution={timing:{duration_ms:10},retry:{count:2},recovery:{provider_internal_retry_count:2,fresh_execution_retry_count:1},effort:null,configured_effort:"max"};const rec=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>result(req,{status:"unavailable",provider_results:[provider({status:"failed",error:{code:"PROCESS_TIMEOUT"},execution})],error:{code:"PROCESS_TIMEOUT"}})});const saved=JSON.parse(readFileSync(rec.path));expect(saved.provider_results[0]).toMatchObject({status:"failed",error:{code:"PROCESS_TIMEOUT"},execution});expect(saved.status).toBe("unavailable");});
 it("stores task-relative raw originals from the real fallback writer and validates the saved result",async()=>{const dir=task(),raw="Owned synthetic raw stderr\n";const rec=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>result(req,{status:"unavailable",provider_results:[provider({status:"failed",error:{code:"PROCESS_CANCELLED",message:"Owned synthetic cancellation fixture"},raw_output:raw})]})});const saved=JSON.parse(readFileSync(rec.path));const member=saved.provider_results[0];expect(member.raw_output_ref).toMatch(/^quality\/reviews\/[a-z0-9.-]+$/);expect(readFileSync(join(dir,member.raw_output_ref),"utf8")).toBe(raw);expect(member).not.toHaveProperty("raw_output");expect(()=>validateSchema("result",saved)).not.toThrow();});
 it("retains existing broker attestation while referencing a single local raw original",async()=>{const dir=task(),stdout="Owned synthetic stdout\n",stderr="Owned synthetic stderr\n",sha=text=>createHash("sha256").update(text).digest("hex");const attestation={version:"broker-output-ref.v1",runtime_id:"fixture-runtime",provider:"fixture/model",stdout_sha256:sha(stdout),stderr_sha256:sha(stderr)};const rec=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>result(req,{status:"unavailable",provider_results:[provider({status:"failed",error:{code:"PROCESS_CANCELLED",message:"Owned synthetic cancellation fixture"},output:stdout,raw_output:stderr,raw_output_ref:attestation})]})});const saved=JSON.parse(readFileSync(rec.path)),member=saved.provider_results[0];expect(member.raw_output_ref).toEqual(attestation);expect(member.evidence_refs).toHaveLength(1);expect(member.evidence_refs[0]).toMatch(/^quality\/reviews\/[a-z0-9.-]+$/);expect(readFileSync(join(dir,member.evidence_refs[0]),"utf8")).toBe(stderr);expect(readFileSync(member.output_ref,"utf8")).toBe(stdout);expect(()=>validateSchema("result",saved)).not.toThrow();});
 it("records new real calls for the same scope instead of reusing an old unavailable fact",async()=>{const dir=task();let calls=0;const runRound=async req=>{calls++;return result(req,{status:"unavailable",error:{code:"OUTPUT_INVALID"}});};const first=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound});const second=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound});expect(calls).toBe(2);expect(first.result_ref).not.toBe(second.result_ref);expect(second.status).toBe("unavailable");expect(JSON.parse(readFileSync(second.path))).toMatchObject({error:{code:"OUTPUT_INVALID"}});});
 it("does not invent dispatch for a preparation exception and propagates storage errors",async()=>{const dir=task();const record=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async()=>{throw Object.assign(new Error("prepare failed"),{code:"PREPARATION_FAILED"});}});expect(JSON.parse(readFileSync(record.path))).toMatchObject({status:"unavailable",dispatch_state:"unknown",error:{code:"PREPARATION_FAILED"}});await expect(recordSimpleReviewRequest({taskDir:join(dir,"missing"),request:request()})).rejects.toMatchObject({code:"ENOENT"});});
 it("rejects a quality symlink before creating a directory outside its task",async()=>{const dir=task(),outside=root();symlinkSync(outside,join(dir,"quality"));let calls=0;await expect(recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>{calls++;return result(req);}})).rejects.toMatchObject({code:"REVIEW_PATH_ALIAS"});expect(calls).toBe(0);expect(existsSync(join(outside,"reviews"))).toBe(false);});
 it("rejects hardlinked task manifests and incomplete/mismatched phase subjects before false advice",async()=>{const dir=task();linkSync(join(dir,"task.json"),join(dir,"second.json"));await expect(recordSimpleReviewRequest({taskDir:dir,request:request()})).rejects.toMatchObject({code:"REVIEW_PATH_INVALID"});const other=task();await expect(recordSimpleReviewRequest({taskDir:other,request:{...request(),phase_id:null}})).rejects.toMatchObject({code:"REVIEW_SUBJECT_INVALID"});await expect(recordSimpleReviewRequest({taskDir:other,request:request(),runRound:async req=>result(req,{subject_kind:"worktree"})})).rejects.toMatchObject({code:"REVIEW_SUBJECT_MISMATCH"});});
 it("preserves provider and finding tags while validating serious evidence",async()=>{const dir=task();const finding={provider:"fixture/model",severity:"important",path:"material.md",line:1,issue:"Real gap",recommendation:"Fix it",root_cause:"Missing condition",evidence_kind:"direct",evidence:"material.md:1",disposition:"actionable",role:"red"};const record=await recordSimpleReviewRequest({taskDir:dir,request:request(),runRound:async req=>result(req,{findings:[finding],adjudication:{version:"wh-review-adjudication.v1",clusters:[]}})});const saved=JSON.parse(readFileSync(record.path));expect(saved.findings[0]).toEqual({...finding,severity:"major"});expect(()=>validateSchema("result",saved)).not.toThrow();});
 it("keeps bare review to one invocation and exposes unavailable instead of fake empty success",async()=>{let calls=0;const value=await runReviewRecovery(request(),{runRound:async req=>{calls++;return result(req,{status:"unavailable",error:{code:"PROVIDER_NO_TERMINAL_RESULT"}});}});expect(calls).toBe(1);expect(value).toMatchObject({status:"unavailable",error:{code:"PROVIDER_NO_TERMINAL_RESULT"}});await expect(runReviewRecovery(request(),{sameSourceFallback:()=>({status:"available"})})).rejects.toThrow(/retired/);});
 it("public CLI reads real task/worktree/input bytes and records phase advice without a kernel writer",async()=>{
  const base=root(),repo=join(base,"repo"),work=join(base,"worktree"),storage=join(base,"storage"),taskDir=join(storage,"Projects","workflowhub","tasks","public-review-fixture");mkdirSync(repo);mkdirSync(taskDir,{recursive:true});
  const git=(cwd,args)=>execFileSync("git",args,{cwd,encoding:"utf8",stdio:["ignore","pipe","pipe"],env:{...process.env,GIT_CONFIG_GLOBAL:"/dev/null",GIT_CONFIG_SYSTEM:"/dev/null",GIT_CONFIG_NOSYSTEM:"1"}}).trim();git(repo,["init","-q","-b","main"]);git(repo,["config","user.name","Owned review fixture"]);git(repo,["config","user.email","fixture@local.invalid"]);writeFileSync(join(repo,"README.md"),"owned temporary Git fixture\n");git(repo,["add","README.md"]);git(repo,["commit","-qm","fixture"]);git(repo,["worktree","add","-q","-b","task/workflowhub/public-review-fixture",work,"main"]);
  writeFileSync(join(taskDir,"task.json"),JSON.stringify({schema_version:"1.0.0",project_name:"workflowhub",task_id:"public-review-fixture",created_at:"2026-10-02T00:00:00.000Z",target_repo_root:repo,workspace_mode:"existing",workspace_root:work,activation_cohort:"post",issue_ids:[],inputs:{},record_model:"vnext-single-write"}));writeFileSync(join(taskDir,"facts.jsonl"),"");const input=join(base,"input.json");writeFileSync(input,JSON.stringify({request:request()}));const old=process.env.WORKFLOWHUB_TASK_DIR;process.env.WORKFLOWHUB_TASK_DIR=storage;
  try{let calls=0;const rec=await stageRuntimeCliMain(["review","--action=record","--stage=build-code","--project=workflowhub","--task=public-review-fixture",`--task-path=${taskDir}`,`--input=${input}`],{cwd:work,services:{runReviewRound:async req=>{calls++;return result(req);}}});expect(calls).toBe(1);expect(JSON.parse(readFileSync(rec.path))).toMatchObject({stage:"build-code",subject_kind:"phase",review_scope:"phase",phase_id:"P5"});expect(readFileSync(join(taskDir,"facts.jsonl"),"utf8")).toBe("");writeFileSync(input,JSON.stringify({result:{status:"available",findings:[]}}));await expect(stageRuntimeCliMain(["review","--action=record","--stage=build-code","--project=workflowhub","--task=public-review-fixture",`--input=${input}`],{cwd:work})).rejects.toThrow(/requires a request/);}
  finally{if(old===undefined)delete process.env.WORKFLOWHUB_TASK_DIR;else process.env.WORKFLOWHUB_TASK_DIR=old;}
 });
});
