import {afterEach,describe,expect,it} from "vitest";
import {execFileSync,spawnSync} from "node:child_process";
import {mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync,existsSync,readdirSync,symlinkSync,linkSync} from "node:fs";
import {tmpdir} from "node:os";import{join}from"node:path";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function env(){const e={...process.env};for(const k of Object.keys(e))if(k.startsWith("GIT_"))delete e[k];return e;}
const git=(cwd,...args)=>execFileSync("git",args,{cwd,env:env(),encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"card06-ordinary-consumer-")));roots.push(p);return p;}
function repository(p){mkdirSync(p);git(p,"init","-q","-b","main");git(p,"config","user.name","Owned ordinary test");git(p,"config","user.email","owned@test.invalid");writeFileSync(join(p,"README.md"),"owned baseline\n");git(p,"add",".");git(p,"commit","-qm","baseline");}
import{bootstrapTask}from"../../tools/cli/task-bootstrap.mjs";
const cli=new URL("../../tools/cli/stage-runtime.mjs",import.meta.url).href;
async function fixture(){const r=root(),repo=join(r,"repo"),storage=join(r,"storage"),home=join(r,"home");repository(repo);mkdirSync(storage);mkdirSync(home);const boot=await bootstrapTask({project:"OwnedEntry",task:"current-entry", "target-repo":repo},{env:{HOME:home,WORKFLOWHUB_TASK_DIR:storage},home,cwd:repo});const wt=boot.workspace.worktree_root,material=join(wt,"specs/current-entry");mkdirSync(join(material,"phases"),{recursive:true});for(const[name,text]of Object.entries({"decision-log.md":"# Current decision\n\n## 任务身份\n- **任务类型**：普通任务\n", "spec.md":"# Current specification\n", "phases/index.md":"## Execution Index\n\n| phase | authority ref | semantic anchor | write set | dependency | consumer |\n| --- | --- | --- | --- | --- | --- |\n| `P1` | `phases/P1.md` | owned | README.md | none | build-code |\n", "phases/P1.md":"# Phase P1\n\n### T001 — Owned current task\n"}))writeFileSync(join(material,name),text);git(wt,"add","specs");git(wt,"commit","-qm","owned current materials");return{r,repo,storage,home,wt,material,taskPath:boot.task_path,n:0};}
function call(f,behavior,action,{stage="build-code",input,extra=[],review=false}={}){const argv=[behavior,`--action=${action}`,`--stage=${stage}`,"--project=OwnedEntry","--task=current-entry",`--task-path=${f.taskPath}`,...extra];if(input!==undefined){const p=join(f.wt,`input-${++f.n}.json`);writeFileSync(p,JSON.stringify(input)+"\n");argv.push(`--input=${p}`);}const code=`import{stageRuntimeCliMain}from${JSON.stringify(cli)};try{const value=await stageRuntimeCliMain(JSON.parse(process.argv[1]),${review?'{services:{runReviewRound:async(request,options)=>{await options.onProviderOutput({provider:"owned/stub",output:Buffer.from([0xff,0x00,0x41])});return{status:"unavailable",dispatch_state:"unknown",findings:[],provider_results:[],error:{code:"OWNED_UNAVAILABLE",message:"controlled no-model review"}};}}}':'{}'});console.log(JSON.stringify({ok:true,value}));}catch(error){console.log(JSON.stringify({ok:false,error:{code:error.code??null,message:error.message}}));}`;const result=spawnSync(process.execPath,["--input-type=module","-e",code,JSON.stringify(argv)],{cwd:f.wt,env:{...env(),HOME:f.home,XDG_CONFIG_HOME:join(f.home,".config"),WORKFLOWHUB_TASK_DIR:f.storage},encoding:"utf8",timeout:15000,stdio:["ignore","pipe","pipe"]});expect(result.error).toBeUndefined();expect(result.status).toBe(0);return JSON.parse(result.stdout);}
function originalFacts(f){return readFileSync(join(f.taskPath,"facts.jsonl"));}

describe("ordinary public facts without a reflection completion writer",()=>{
 it("rejects the removed reflect action and machine judgment before any task fact write",async()=>{const f=await fixture(),before=originalFacts(f),input={reflection_status:"ok",receipts:{review:"old"},snapshot_tree:"old-passive-data"};const removed=call(f,"run","reflect",{stage:"build-plan",input});expect(removed).toMatchObject({ok:false,error:{message:"unknown public runtime action"}});const wrong=call(f,"run","execute",{stage:"build-plan",input});expect(wrong.ok).toBe(false);expect(wrong.error.message).toMatch(/only records.*phase_progress/);expect(originalFacts(f)).toEqual(before);expect(existsSync(join(f.taskPath,"quality/stage-reflection"))).toBe(false);});
 it("stores the legitimate cursor with unknown/null quality and keeps human confirmation separate",async()=>{const f=await fixture(),run=call(f,"run","execute",{input:{phase_progress:{phase_id:"P1",task_id:"T001"}}});expect(run.ok).toBe(true);const rows=JSON.parse(originalFacts(f).toString().trim());expect(rows).toMatchObject({record_kind:"stage",stage:"build-code",phase_progress:{phase_id:"P1",task_id:"T001"},review_origin:"not_run",spec_analyze:{value:null},evidence:{value:null}});const before=originalFacts(f),confirm=call(f,"confirm","decision",{stage:"build-plan",extra:["--decision=approved","--reply-text=Only approve this owned plan.","--material-ref=spec.md"]});expect(confirm.ok).toBe(true);expect(originalFacts(f)).toEqual(before);expect(call(f,"status","begin").value.quality_status).toBe("unknown");expect(existsSync(join(f.taskPath,"quality/evidence/git-authorizations"))).toBe(false);});
});
