import { afterEach, describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createTask } from '../../runtime/task/task-handle.mjs';
import { initializeTaskStore, writeStageRow } from '../../runtime/task/task-store.mjs';
const roots=[],taskId='ordinary-status-reader';
const git=(cwd,args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
async function fixture(){const root=realpathSync(mkdtempSync(join(tmpdir(),'workflowhub-status-reader-')));roots.push(root);const repo=join(root,'repo'),worktree=join(root,'worktree'),storage=join(root,'storage'),home=join(root,'home');for(const p of[repo,storage,home])mkdirSync(p);git(repo,['init','-q','-b','main']);git(repo,['config','user.name','Owned status reader']);git(repo,['config','user.email','owned@test.invalid']);git(repo,['commit','--allow-empty','-qm','owned baseline']);git(repo,['worktree','add','-q','-b',`task/workflowhub/${taskId}`,worktree,'main']);const task=await createTask({storageRoot:storage,manifest:{schema_version:'1.0.0',project_name:'workflowhub',task_id:taskId,created_at:'2026-10-03T00:00:00Z',activation_cohort:'post',record_model:'vnext-single-write',execution_mode:'per_invocation',target_repo_root:repo,workspace_mode:'existing',workspace_root:worktree,issue_ids:[],inputs:{}}});await initializeTaskStore(task.taskPath,{taskId});const materials=join(worktree,'specs',taskId);mkdirSync(join(materials,'phases'),{recursive:true});for(const[file,body]of Object.entries({'decision-log.md':'# Decision\r\n','spec.md':'# Spec\n','phases/index.md':'## Execution Index\n\n| phase | authority ref |\n| --- | --- |\n| `P1` | `phases/P1.md` |\n','phases/P1.md':'# Phase P1\n'}))writeFileSync(join(materials,file),body);return{root,repo,worktree,storage,home,task,materials};}
function status(f){const module=new URL('../../tools/cli/stage-runtime.mjs',import.meta.url).href,script=`import {stageRuntimeCliMain} from ${JSON.stringify(module)};try{const value=await stageRuntimeCliMain(JSON.parse(process.argv[1]),{cwd:process.argv[2]});console.log(JSON.stringify({ok:true,value}));}catch(error){console.log(JSON.stringify({ok:false,error:{name:error.name,code:error.code??null,message:error.message}}));}`;const argv=['status','--action=begin','--stage=build-code','--project=workflowhub',`--task=${taskId}`,`--task-path=${f.task.taskPath}`];return JSON.parse(execFileSync(process.execPath,['--input-type=module','-e',script,JSON.stringify(argv),f.worktree],{env:{PATH:'/usr/bin:/bin:/usr/sbin:/sbin',HOME:f.home,XDG_CONFIG_HOME:join(f.home,'.config'),WORKFLOWHUB_TASK_DIR:f.storage},encoding:'utf8',timeout:10000,stdio:['ignore','pipe','pipe']}));}
const bytes=f=>({manifest:readFileSync(join(f.task.taskPath,'task.json')),facts:readFileSync(join(f.task.taskPath,'facts.jsonl'))});
async function named(f,ref='quality/reviews/2026-10-03-owned-reader.json'){await writeStageRow(f.task.taskPath,{stage:'build-code',source:'owned:named-quality-reader',review_origin:'conducted',review_result_ref:ref});return{ref,path:join(f.task.taskPath,ref)};}
describe('current public status reads ordinary facts, not completion projections',()=>{
  it('discloses actual material presence and missing path without manufacturing quality or stage completion',async()=>{const f=await fixture(),before=bytes(f),ready=status(f);expect(ready.ok).toBe(true);expect(ready.value.work_status).toBe('ready');expect(ready.value.materials).toEqual({'decision-log.md':true,'spec.md':true,'phases/index.md':true,'phases/P1.md':true});expect(ready.value.quality_status).toBe('unknown');expect(ready.value.facts).toEqual([]);rmSync(join(f.materials,'spec.md'));const missing=status(f);expect(missing.ok).toBe(true);expect(missing.value.work_status).toBe('not_ready');expect(missing.value.missing_materials).toEqual(['spec.md']);expect(missing.value.quality_status).toBe('unknown');expect(bytes(f)).toEqual(before);for(const result of[ready.value,missing.value])for(const retired of['completed','status_groups','product_release','quality_gaps','release_gaps','close_preparation_gaps','actionable_now'])expect(result).not.toHaveProperty(retired);});
  it.each([['unavailable','unavailable'],['available','incomplete'],['available-with-failures','incomplete'],['incomplete','incomplete']])('reads the real named local %s review fixture as %s without certifying whole-stage completion',async(reviewStatus,quality)=>{const f=await fixture(),n=await named(f),raw=JSON.stringify({task_id:taskId,stage:'build-code',status:reviewStatus})+'\n';writeFileSync(n.path,raw);const before=bytes(f),r=status(f);expect(r.ok).toBe(true);expect(r.value.work_status).toBe('ready');expect(r.value.quality_status).toBe(quality);expect(r.value.quality).toEqual({status:quality,review_origin:'conducted',review_result_ref:n.ref});expect(r.value.facts).toHaveLength(1);expect(r.value).not.toHaveProperty('completed');expect(bytes(f)).toEqual(before);expect(readFileSync(n.path,'utf8')).toBe(raw);});
  it('reads old row fields only as original passive bytes, without creating a completion or stage-outcome authority',async()=>{const f=await fixture(),path=join(f.task.taskPath,'facts.jsonl'),rows=[{task_id:taskId,record_kind:'stage',stage:'build-plan',source:'old:stage-end',snapshot_tree:'a'.repeat(40)},{task_id:taskId,record_kind:'stage',stage:'build-code',source:'old:stage-end',review_origin:'not_run',material_digest:{value:'b'.repeat(64)},layer_states:{implementation_completion:'completed'},completed:true,status_groups:{quality:'completed'}}],raw=rows.map(row=>'  '+JSON.stringify(row)).join('\n')+'\n';writeFileSync(path,raw);const before=bytes(f),r=status(f);expect(r.ok).toBe(true);expect(r.value.facts).toEqual(rows);expect(r.value.quality_status).toBe('unknown');expect(r.value.work_status).toBe('ready');for(const retired of['completed','status_groups','product_release'])expect(r.value).not.toHaveProperty(retired);expect(bytes(f)).toEqual(before);expect(readFileSync(path,'utf8')).toBe(raw);});
  it('keeps absent named review unknown and exposes malformed or wrong-identity named source errors without mutation',async()=>{const f=await fixture(),n=await named(f),before=bytes(f),absent=status(f);expect(absent.ok).toBe(true);expect(absent.value.quality_status).toBe('unknown');for(const[raw,name,message]of[['{not JSON}\n','SyntaxError',null],[JSON.stringify({task_id:'foreign-task',stage:'build-code',status:'available'})+'\n','Error','review result differs from current row identity'],[JSON.stringify({task_id:taskId,stage:'verify-code',status:'available'})+'\n','Error','review result differs from current row identity']]){writeFileSync(n.path,raw);const r=status(f);expect(r.ok).toBe(false);expect(r.error.name).toBe(name);if(message)expect(r.error.message).toBe(message);expect(readFileSync(n.path,'utf8')).toBe(raw);expect(bytes(f)).toEqual(before);} });
});
