// Actual UI source facts and verbatim human records remain; retired render/snapshot certification is not rebuilt.
import{afterEach,expect,it}from"vitest";import{execFileSync}from"node:child_process";import{mkdirSync,mkdtempSync,readFileSync,realpathSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";
import{readUiApplicabilityFromDecisionLog,validateUiApplicability}from"../../runtime/stage/stage-content-contracts.mjs";import{recordConfirmation}from"../../runtime/interface/human-confirm.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
const sources=value=>Object.fromEntries(["raw_requirement","project_inventory","planned_or_changed_frontend_fact"].map(k=>[k,{conclusion:value,reason:"Real declared source fact"}]));const log=f=>"# Current decision\n\n## UI applicability\n```json\n"+JSON.stringify(f)+"\n```\n";
it("reads logged UI without silently substituting a missing implementation or renderer as non-UI",()=>{expect(readUiApplicabilityFromDecisionLog(log({result:"ui",sources:sources("ui")}))).toMatchObject({status:"recorded",applicability:"ui"});});
it("preserves logged non-UI and exposes absent decision facts as unknown",()=>{expect(readUiApplicabilityFromDecisionLog(log({result:"non_ui",sources:sources("non_ui")}))).toMatchObject({status:"recorded",applicability:"non_ui"});expect(readUiApplicabilityFromDecisionLog("# Missing fact")).toMatchObject({status:"missing",applicability:"unknown"});});
it("rejects conflicting, missing or malformed source facts rather than suppressing the UI question",()=>{const mixed=sources("non_ui");mixed.raw_requirement={conclusion:"ui",reason:"User requested a page"};expect(validateUiApplicability({result:"non_ui",sources:mixed}).ok).toBe(false);expect(validateUiApplicability({result:"ui",sources:{raw_requirement:uiSource()}}).ok).toBe(false);expect(readUiApplicabilityFromDecisionLog("## UI applicability\n```json\n{broken\n```\n").status).toBe("missing");});
function uiSource(){return{conclusion:"ui",reason:"User requested UI"};}
it("keeps uncertain UI unresolved even if a caller writes a generic approval label",()=>{const r=readUiApplicabilityFromDecisionLog(log({result:"unknown",sources:sources("unknown"),reason:"No source decision",handoff:"make-decision",user_question:"Does this change a page?",confirmation:"human_approved"}));expect(r.status).toBe("missing");expect(r.applicability).toBe("unknown");expect(r.missing_items.length).toBeGreaterThan(0);});
it("records actual Git HEAD, exact design material reference and verbatim user reply without a completion claim",async()=>{const root=realpathSync(mkdtempSync(join(tmpdir(),"ui-human-record-")));roots.push(root);const repo=join(root,"repo"),dir=join(root,"records");mkdirSync(repo);mkdirSync(dir);const env={...process.env};for(const k of Object.keys(env))if(k.startsWith("GIT_"))delete env[k];const git=args=>execFileSync("git",args,{cwd:repo,env,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();git(["init","-q","-b","main"]);git(["config","user.name","Owned UI"]);git(["config","user.email","owned@test.invalid"]);writeFileSync(join(repo,"design.svg"),"<svg xmlns='http://www.w3.org/2000/svg'></svg>");git(["add","design.svg"]);git(["commit","-qm","design"]);const r=await recordConfirmation({stage:"build-plan",decision:"confirmed",reply:"I approve this displayed design.",materialRefs:["design.svg"]},{cwd:repo,dir});const actual=JSON.parse(readFileSync(r.path,"utf8"));expect(actual).toMatchObject({head:git(["rev-parse","HEAD"]),reply:"I approve this displayed design.",material_refs:["design.svg"],decision:"confirmed"});expect(actual).not.toHaveProperty("completion");await expect(recordConfirmation({stage:"build-plan",decision:"confirmed",reply:"",materialRefs:["design.svg"]},{cwd:repo,dir})).rejects.toMatchObject({code:"CONFIRMATION_REPLY_REQUIRED"});});
