import {afterEach,describe,expect,it} from "vitest";
import {mkdtempSync,realpathSync,rmSync,writeFileSync,linkSync,symlinkSync} from "node:fs";
import {join} from "node:path";import {tmpdir} from "node:os";
import {MAX_REVIEWER_OUTPUT_BYTES,parseReviewerOutput} from "../../../../runtime/review/review-output.mjs";
import {aggregateCanonicalProviderResults} from "../../../../runtime/review/canonical-review-result.mjs";
import {actionableSeriousFindings,planDirectionReviewRequests,reviewCycleDecision,verifyFinal,verifyFinalSubject} from "../review-runner.mjs";
import {createSimpleReviewPacket,dispatchFrozenProviderInput,serializeProviderInput} from "../simple-review-runner.mjs";
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function root(){const p=realpathSync(mkdtempSync(join(tmpdir(),"wh-review-query-")));roots.push(p);return p;}
const finding={severity:"major",path:"src/app.mjs",line:1,issue:"Unsafe mutation",recommendation:"Guard the real mutation",root_cause:"Missing guard",evidence_kind:"direct",evidence:"src/app.mjs:1",disposition:"actionable"};
const semantic=()=>({status:"available",stage:"build-code",review_scope:"phase",subject_kind:"phase",phase_id:"P5",task_id:"fixture",provider_results:[{provider:"fixture/model",status:"completed",identity:{provider:"fixture/model",source_id:"fixture-source",config_id:"fixture-config"}}],findings:[{...finding,provider:"fixture/model"}]});
describe("current wh-review query, parser and disposition",()=>{
 it("accepts one JSON object and rejects malformed or oversized reviewer output",()=>{const empty=JSON.stringify({findings:[]});expect(parseReviewerOutput(empty)).toEqual({findings:[]});expect(parseReviewerOutput(`note\n\`\`\`json\n${empty}\n\`\`\``)).toEqual({findings:[]});expect(()=>parseReviewerOutput("not json")).toThrow(/OUTPUT_INVALID/);const exact=empty+" ".repeat(MAX_REVIEWER_OUTPUT_BYTES-Buffer.byteLength(empty));expect(parseReviewerOutput(exact)).toEqual({findings:[]});expect(()=>parseReviewerOutput(exact+"x")).toThrow(/exceeds/);});
 it("retains unknown severity as discarded facts and rejects unsafe anchors or absent serious evidence",()=>{expect(parseReviewerOutput(JSON.stringify({findings:[{...finding,severity:"unexpected"}]})).discarded_facts).toHaveLength(1);expect(()=>parseReviewerOutput(JSON.stringify({findings:[{...finding,path:"/Users/private.mjs"}]}),{requireEvidence:true})).toThrow(/OUTPUT_INVALID/);expect(()=>parseReviewerOutput(JSON.stringify({findings:[{...finding,root_cause:undefined}]}),{requireEvidence:true})).toThrow(/OUTPUT_INVALID/);});
 it("unions providers and roles without requiring consensus",()=>{const result=aggregateCanonicalProviderResults([{provider:"kimi",role:"red",review:{findings:[finding]},evidenceAnchors:[true]},{provider:"claude",role:"blue",review:{findings:[]}}],1);expect(result.findings).toHaveLength(1);expect(result.adjudication.clusters[0]).toMatchObject({providers:["kimi"],roles:["blue","red"],consensus:false});});
 it("keeps invalid anchor facts conservative instead of declaring the finding passed",()=>{const result=aggregateCanonicalProviderResults([{provider:"kimi",review:{findings:[finding]},evidenceAnchors:[true]},{provider:"claude",review:{findings:[finding]},evidenceAnchors:[false]}],1);expect(result.adjudication.clusters[0].disposition).toBe("actionable");});
 it("deduplicates actual serious advice and preserves unavailable/incomplete",()=>{const result=semantic();result.adjudication={clusters:result.findings};expect(actionableSeriousFindings(result)).toHaveLength(1);expect(reviewCycleDecision({stage:"build-code",result})).toMatchObject({status:"advice_recorded",action:"advance"});expect(reviewCycleDecision({stage:"build-code",result:{status:"unavailable",findings:[]}})).toMatchObject({status:"incomplete",reason:"provider_no_trusted_terminal_result"});});
 it("uses one direction request with broker-owned reconstruct reveal challenge",()=>{const planned=planDirectionReviewRequests({raw_requirement:"A real need",objective_facts:{known:true},current_selection:"Selected direction"});expect(planned.requests).toHaveLength(1);expect(planned.flow.steps.map(s=>s.id)).toEqual(["reconstruct","reveal","challenge"]);expect(planned.flow.steps[0]).toMatchObject({hidden_until:"reveal",visible:["raw_requirement","objective_facts"]});});
 it("reads explicit historical advice without granting current snapshot finalization",()=>{const result=semantic();expect(verifyFinalSubject({result,current:{snapshotTree:"changed"},taskId:"fixture",stage:"build-code"})).toMatchObject({status:"available",authoritative:false,subject_kind:"phase",phase_id:"P5"});expect(()=>verifyFinalSubject({result:{...result,reviewScope:"integration"}})).toThrow(/aliases .*disagree/);expect(()=>verifyFinalSubject({result,taskId:"other"})).toThrow(/task does not match/);expect(verifyFinalSubject({result:{...result,status:"unavailable",findings:[],error:{code:"OUTPUT_INVALID"}}})).toMatchObject({status:"unavailable"});});
 it("requires a safe explicit single-link result and preserves malformed bytes",()=>{const dir=root();const path=join(dir,"quality/reviews");return import("node:fs").then(({mkdirSync,readFileSync})=>{mkdirSync(path,{recursive:true});const file=join(path,"one.json");writeFileSync(file,JSON.stringify(semantic()));expect(verifyFinal({taskDir:dir,resultRef:"quality/reviews/one.json"})).toMatchObject({status:"available",authoritative:false});linkSync(file,join(path,"hard.json"));expect(()=>verifyFinal({taskDir:dir,resultRef:"quality/reviews/one.json"})).toThrow(/single-link/);writeFileSync(join(path,"bad.json"),"{bad");expect(()=>verifyFinal({taskDir:dir,resultRef:"quality/reviews/bad.json"})).toThrow();expect(readFileSync(join(path,"bad.json"),"utf8")).toBe("{bad");expect(()=>verifyFinal({taskDir:dir,resultRef:"../one.json"})).toThrow(/explicit task-local/);});});
 it("rejects malformed serialized material before dispatch rather than using hash permits",async()=>{const dir=root();const packet=createSimpleReviewPacket({stage:"make-decision",review_track:"detail",materials:{raw_requirement:"Plain sample"}});const value=JSON.parse(serializeProviderInput({packet,providers:["fixture/model"],reviewMode:"single_round"}));value.packet.materials[0].content_base64="/w==";let calls=0;await expect(dispatchFrozenProviderInput({bytes:Buffer.from(JSON.stringify(value)),attachmentRoot:dir,client:{async runGroup(){calls++;}}})).rejects.toThrow();expect(calls).toBe(0);expect(packet).not.toHaveProperty("material_id");expect(value).not.toHaveProperty("envelope_sha256");});
});
