import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { prepareDeliveryClosePlan, confirmClosePlan, authorizeClosePlan, executeClosePlan, inspectDeliveryCloseState, closeDelivery } from "../../core/task-close.mjs";
const roots=[];let counter=0;
afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true});});
function git(root,args){return execFileSync("git",args,{cwd:root,encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();}
function fixture({existing=false,remoteTask=true}={}){
  const base=realpathSync(mkdtempSync(join(tmpdir(),"workflowhub-close-narrow-")));roots.push(base);
  const repo=join(base,"repo"),bare=join(base,"origin.git"),id=`close-${++counter}`,worktree=join(base,`repo-${id}`),taskDir=join(base,"storage","Projects","workflowhub","tasks",id);
  mkdirSync(repo);mkdirSync(bare);mkdirSync(taskDir,{recursive:true});
  git(repo,["init","-q","-b","main"]);git(repo,["config","user.name","Owned close fixture"]);git(repo,["config","user.email","fixture@local.invalid"]);
  const hooks=join(base,"hooks");mkdirSync(hooks);git(repo,["config","core.hooksPath",hooks]);
  writeFileSync(join(repo,"README.md"),"base\n");git(repo,["add","README.md"]);git(repo,["commit","-qm","base"]);
  git(bare,["init","--bare","-q"]);git(repo,["remote","add","origin",bare]);git(repo,["push","-q","origin","main"]);
  const branch=`task/workflowhub/${id}`;git(repo,["worktree","add","-q","-b",branch,worktree,"main"]);
  const source=`specs/${id}`;mkdirSync(join(worktree,source),{recursive:true});writeFileSync(join(worktree,source,"decision-log.md"),"# Decision\n");writeFileSync(join(worktree,source,"spec.md"),"# Spec\n");
  git(worktree,["add",source]);git(worktree,["commit","-qm","materials"]);if(remoteTask)git(worktree,["push","-q","origin",branch]);
  writeFileSync(join(taskDir,"task.json"),JSON.stringify({schema_version:"1.0.0",project_name:"workflowhub",task_id:id,created_at:"2026-10-02T00:00:00Z",target_repo_root:repo,record_model:"vnext-single-write",activation_cohort:"post",...(existing?{workspace_mode:"existing",workspace_root:worktree}:{})})+"\n");
  writeFileSync(join(taskDir,"facts.jsonl"),"");
  return {base,repo,bare,worktree,id,taskDir,branch,source,delivery:{remote:"origin",target_branch:"main",task_branch:branch,spec_source_path:source,spec_archive_path:`specs/archive/${id}`}};
}
async function prepare(s,mode){return prepareDeliveryClosePlan({taskDir:s.taskDir,delivery:s.delivery,...(mode?{closeMode:mode}:{})});}
async function confirm(s,p,outcome="confirmed",replyText="Owned fixture explicit reply"){return confirmClosePlan({taskDir:s.taskDir,planRef:p.plan_ref,outcome,replyText});}
async function authorized(s,p){const c=await confirm(s,p);await authorizeClosePlan({taskDir:s.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});return c;}
async function execute(s,p,c){return executeClosePlan({taskDir:s.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref});}

describe("close actual transactions without retired workflow permits",()=>{
 it("reports missing quality as unknown and stores a single ordinary explicit plan reference",async()=>{const s=fixture(),p=await prepare(s);expect(p.quality_status).toBe("unknown");expect(p.plan_ref).toMatch(/\d{4}-\d{2}-\d{2}-\d{3}-close-plan\.json$/);expect(p.plan).not.toHaveProperty("plan_hash");expect(p.plan).not.toHaveProperty("snapshot_tree");expect(JSON.parse(readFileSync(p.plan_ref))).toEqual(p.plan);});
 it("requires an actual verbatim reply and keeps timeout distinct from confirmation",async()=>{const s=fixture(),p=await prepare(s);await expect(confirm(s,p,"confirmed","")).rejects.toThrow(/reply/);const c=await confirmClosePlan({taskDir:s.taskDir,planRef:p.plan_ref,outcome:"timeout"});expect(c.status).toBe("blocked");expect(JSON.parse(readFileSync(c.confirmation_ref))).not.toHaveProperty("reply");});
 it("rejects unrecorded Git authorization without changing source or target HEAD",async()=>{const s=fixture(),p=await prepare(s),c=await confirm(s,p),a=git(s.worktree,["rev-parse","HEAD"]),b=git(s.repo,["rev-parse","HEAD"]);const out=await execute(s,p,c);expect(out.status).toBe("failed");expect(out.error.code).toBe("IRREVERSIBLE_AUTHORIZATION_REQUIRED");expect(git(s.worktree,["rev-parse","HEAD"])).toBe(a);expect(git(s.repo,["rev-parse","HEAD"])).toBe(b);});
 it("preserves exactly five actions and reads their real physical results after owned cleanup",async()=>{const s=fixture(),p=await prepare(s);expect(p.plan.steps).toEqual(["commit","merge","archive","push","cleanup"]);const c=await authorized(s,p),out=await execute(s,p,c);expect(out.status).toBe("completed");expect(out.records.map(r=>r.operation)).toEqual(p.plan.steps);expect(existsSync(s.worktree)).toBe(false);expect(git(s.repo,["cat-file","-e",`main:specs/archive/${s.id}/spec.md`])).toBe("");const readback=await inspectDeliveryCloseState({taskDir:s.taskDir,planRef:p.plan_ref});for(const flag of ["delivery_committed","merge","archive","push","worktree_cleanup","branch_cleanup","remote_branch_cleanup"])expect(readback.facts[flag],flag).toBe(true);});
 it("captures dirty source before planning but rejects later bytes drifting from that plan",async()=>{const s=fixture();writeFileSync(join(s.worktree,"changed.txt"),"first\n");const p=await prepare(s);expect(p.plan.source.changes.map(r=>r.path)).toContain("changed.txt");const c=await authorized(s,p);writeFileSync(join(s.worktree,"changed.txt"),"second\n");const out=await execute(s,p,c);expect(out.status).toBe("failed");expect(out.error.code).toBe("SOURCE_BYTES_DRIFT");expect(readFileSync(join(s.worktree,"changed.txt"),"utf8")).toBe("second\n");});
 it("rejects dirty target before performing any source commit",async()=>{const s=fixture();writeFileSync(join(s.worktree,"change.txt"),"planned\n");const p=await prepare(s),c=await authorized(s,p),head=git(s.worktree,["rev-parse","HEAD"]);writeFileSync(join(s.repo,"unrelated.txt"),"user-owned\n");await expect(execute(s,p,c)).rejects.toThrow(/clean|dirty/i);expect(git(s.worktree,["rev-parse","HEAD"])).toBe(head);expect(readFileSync(join(s.repo,"unrelated.txt"),"utf8")).toBe("user-owned\n");});
 it("keeps existing worktrees and branches while marking cleanup skipped",async()=>{const s=fixture({existing:true}),p=await prepare(s),c=await authorized(s,p),out=await execute(s,p,c);expect(out.status).toBe("completed");expect(out.records.find(r=>r.operation==="cleanup").status).toBe("skipped");expect(existsSync(s.worktree)).toBe(true);expect(git(s.repo,["rev-parse",`refs/heads/${s.branch}`])).not.toBe("");});
 it("keeps the four-action planning route without automatically archiving its materials",async()=>{const s=fixture(),p=await prepare(s,"planning");expect(p.plan.steps).toEqual(["commit","merge","push","cleanup"]);const c=await authorized(s,p),out=await execute(s,p,c);expect(out.status).toBe("executed");expect(git(s.repo,["cat-file","-e",`main:${s.source}/spec.md`])).toBe("");});
 it("one-shot close executes actual five-action Git delivery after the real reply",async()=>{const s=fixture();const out=await closeDelivery({taskDir:s.taskDir,delivery:s.delivery,replyText:"Owned fixture: execute all displayed five actions"});expect(out.status).toBe("completed");expect(existsSync(s.worktree)).toBe(false);expect(git(s.repo,["cat-file","-e",`main:specs/archive/${s.id}/spec.md`])).toBe("");});
 it("reads the current planning task declaration and defaults to four actions",async()=>{const s=fixture();writeFileSync(join(s.worktree,s.source,"decision-log.md"),"# Decision\n\n## 任务身份\n- **任务类型**：规划任务\n");const p=await prepare(s);expect(p.plan.steps).toEqual(["commit","merge","push","cleanup"]);const out=await closeDelivery({taskDir:s.taskDir,delivery:s.delivery,replyText:"Owned fixture: execute four actions and leave materials"});expect(out.status).toBe("executed");expect(git(s.repo,["cat-file","-e",`main:${s.source}/spec.md`])).toBe("");expect(existsSync(join(s.repo,`specs/archive/${s.id}`))).toBe(false);});
 it("requires an explicit same-task archive declaration before the later two-action close",async()=>{const s=fixture();writeFileSync(join(s.worktree,s.source,"decision-log.md"),"# Decision\n\n## 任务身份\n- **任务类型**：规划任务\n");const out=await closeDelivery({taskDir:s.taskDir,delivery:s.delivery,replyText:"Owned fixture: planning delivery only"});expect(out.status).toBe("executed");const declaration=join(s.taskDir,"quality","evidence","archive-request.json");writeFileSync(declaration,JSON.stringify({task_id:"another-task",workflow:"build-prd",reply_text:"现在明确下令归档"}));await expect(prepareDeliveryClosePlan({taskDir:s.taskDir,priorPlanRef:out.plan_ref,archiveDeclarationRef:declaration})).rejects.toMatchObject({code:"ARCHIVE_DECLARATION"});writeFileSync(declaration,JSON.stringify({task_id:s.id,workflow:"build-prd",reply_text:"禁止归档"}));await expect(prepareDeliveryClosePlan({taskDir:s.taskDir,priorPlanRef:out.plan_ref,archiveDeclarationRef:declaration})).rejects.toMatchObject({code:"ARCHIVE_DECLARATION"});for(const status of ["in_progress","unknown","blocked","cancelled"]){writeFileSync(declaration,JSON.stringify({task_id:s.id,workflow:"build-prd",reply_text:"现在明确下令归档",step_results:[{status}]}));await expect(prepareDeliveryClosePlan({taskDir:s.taskDir,priorPlanRef:out.plan_ref,archiveDeclarationRef:declaration})).rejects.toMatchObject({code:"ARCHIVE_DECLARATION_INCOMPLETE"});}writeFileSync(declaration,JSON.stringify({task_id:s.id,workflow:"build-prd",reply_text:"现在明确下令归档"}));const p=await prepareDeliveryClosePlan({taskDir:s.taskDir,priorPlanRef:out.plan_ref,archiveDeclarationRef:declaration});expect(p.plan.steps).toEqual(["archive","push"]);const c=await confirm(s,p);await authorizeClosePlan({taskDir:s.taskDir,planRef:p.plan_ref,confirmationRef:c.confirmation_ref,operations:["push"]});const denied=await execute(s,p,c);expect(denied.status).toBe("failed");expect(denied.error.code).toBe("IRREVERSIBLE_AUTHORIZATION_REQUIRED");expect(existsSync(join(s.repo,s.source))).toBe(true);expect(existsSync(join(s.repo,`specs/archive/${s.id}`))).toBe(false);const archive=await closeDelivery({taskDir:s.taskDir,priorPlanRef:out.plan_ref,archiveDeclarationRef:declaration,replyText:"Owned fixture: execute the displayed archive and push"});expect(archive.status).toBe("completed");expect(git(s.repo,["cat-file","-e",`main:specs/archive/${s.id}/spec.md`])).toBe("");});
 it("supports the actual existing-worktree manifest whose declared target is that source worktree",async()=>{const s=fixture({existing:true});const path=join(s.taskDir,"task.json"),manifest=JSON.parse(readFileSync(path));manifest.target_repo_root=s.worktree;writeFileSync(path,JSON.stringify(manifest));const p=await prepare(s);expect(p.plan.target_repo_root).toBe(s.repo);expect(p.plan.worktree_root).toBe(s.worktree);const out=await closeDelivery({taskDir:s.taskDir,delivery:s.delivery,replyText:"Owned fixture: preserve existing source, deliver to actual main"});expect(out.status).toBe("completed");expect(existsSync(s.worktree)).toBe(true);});
});
